# IMPORT LIBRARY

In [1]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import warnings

In [2]:
warnings.simplefilter('ignore')
pd.set_option('display.max_columns', None)

# DATASET

Dataset : E-Commerce Public Dataset.

Link : https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce

Dataset ini mencakup informasi yang dikumpulkan dari transaksi e-commerce di Brazil dalam rentang waktu tertentu. Dataset tersebut terdiri dari beberapa file yang terkait satu sama lain dan memberikan wawasan yang komprehensif tentang industri e-commerce di Brazil.

Deskripsi file dataset yang digunakan dalam analisis ini adalah sebagai berikut,

- orders_dataset : 
    
    File ini berisi informasi tentang pesanan, seperti ID pesanan, status pesanan, waktu pembelian, dan waktu pengiriman pesanan.

- order_items_dataset :

    File ini berisi informasi terperinci tentang setiap item yang dibeli dalam pesanan

- order_payments_dataset :

    File ini berisi informasi terperinci tentang jenis pembayaran yang digunakan dari setiap item yang dibeli dalam pesanan

- order_reviews_dataset :

    File ini berisi informasi terperinci tentang review dari setiap item yang dibeli dalam pesanan

- products_dataset :

    File ini berisi informasi tentang produk, termasuk ID produk dan nama produk.

- product_category_dataset :

    File ini berisi informasi tentang kategori produk, termasuk ID produk dan kategori produk.

- sellers_dataset :

    File ini berisi informasi tentang penjual, seperti ID penjual, nama penjual, dan lokasi penjual (kota dan negara bagian).

- customers_dataset :

    File ini berisi informasi tentang pelanggan, seperti ID pelanggan, nama pelanggan, dan lokasi pelanggan (kota dan negara bagian).

- geolocation_dataset :

    File ini menyediakan informasi geografis tentang kota dan negara bagian di Brazil. Ini membantu dalam analisis berdasarkan lokasi geografis.

### Customer Dataset

In [3]:
df_customer = pd.read_csv('data/customers_dataset.csv')
df_customer.head()

customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0   
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3   
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e   
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c   
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066   

   customer_zip_code_prefix          customer_city customer_state  
0                     14409                 franca             SP  
1                      9790  sao bernardo do campo             SP  
2                      1151              sao paulo             SP  
3                      8775        mogi das cruzes             SP  
4                     13056               campinas             SP

In [4]:
df_customer.shape

(99441, 5)

### Order Dataset

In [5]:
df_order = pd.read_csv('data/orders_dataset.csv')
df_order.head()

order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d   
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef   
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089   
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82   
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c   

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15   
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27   
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23   
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59   
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29   

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13   
1          2018-07-26 14:31:00           2018-08-07 15:27:45   
2          2018-08-08 13:50:00           2018-08-17 18:06:29   
3          2017-11-22 13:39:59           2017-12-02 00:28:42   
4          2018-02-14 19:46:34           2018-02-16 18:17:02   

  order_estimated_delivery_date  
0           2017-10-18 00:00:00  
1           2018-08-13 00:00:00  
2           2018-09-04 00:00:00  
3           2017-12-15 00:00:00  
4           2018-02-26 00:00:00

In [6]:
df_order.shape

(99441, 8)

In [7]:
df_order_items = pd.read_csv('data/order_items_dataset.csv')
df_order_items.head()

order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1   
1  00018f77f2f0320c557190d7a144bdd3              1   
2  000229ec398224ef6ca0657da4fc703e              1   
3  00024acbcdf0a6daa1e931b038114c75              1   
4  00042b26cf59d7ce69dfabb4e55b4fd9              1   

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202   
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36   
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d   
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4   
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87   

   shipping_limit_date   price  freight_value  
0  2017-09-19 09:45:35   58.90          13.29  
1  2017-05-03 11:05:13  239.90          19.93  
2  2018-01-18 14:48:30  199.00          17.87  
3  2018-08-15 10:10:18   12.99          12.79  
4  2017-02-13 13:57:51  199.90          18.14

In [8]:
df_order_items.shape

(112650, 7)

In [9]:
df_order_payments = pd.read_csv('data/order_payments_dataset.csv')
df_order_payments.head()

order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card   
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card   
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card   
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card   
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card   

   payment_installments  payment_value  
0                     8          99.33  
1                     1          24.39  
2                     1          65.71  
3                     8         107.78  
4                     2         128.45

In [10]:
df_order_payments.shape

(103886, 5)

In [11]:
df_order_review = pd.read_csv('data/order_reviews_dataset.csv')
df_order_review.head()

review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb   
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33   
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b   
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b   
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1   

   review_score review_comment_title  \
0             4                  NaN   
1             5                  NaN   
2             5                  NaN   
3             5                  NaN   
4             5                  NaN   

                              review_comment_message review_creation_date  \
0                                                NaN  2018-01-18 00:00:00   
1                                                NaN  2018-03-10 00:00:00   
2                                                NaN  2018-02-17 00:00:00   
3              Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00   
4  Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00   

  review_answer_timestamp  
0     2018-01-18 21:46:59  
1     2018-03-11 03:05:13  
2     2018-02-18 14:36:24  
3     2017-04-21 22:02:06  
4     2018-03-02 10:26:53

In [12]:
df_order_review.shape

(99224, 7)

### Products Dataset

In [13]:
df_product = pd.read_csv('data/products_dataset.csv')
df_product.head()

product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria   
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes   
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer   
3  cef67bcfe19066a932b7673e239eb23d                  bebes   
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas   

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0   
1                 44.0                       276.0                 1.0   
2                 46.0                       250.0                 1.0   
3                 27.0                       261.0                 1.0   
4                 37.0                       402.0                 4.0   

   product_weight_g  product_length_cm  product_height_cm  product_width_cm  
0             225.0               16.0               10.0              14.0  
1            1000.0               30.0               18.0              20.0  
2             154.0               18.0                9.0              15.0  
3             371.0               26.0                4.0              26.0  
4             625.0               20.0               17.0              13.0

In [14]:
df_product.shape

(32951, 9)

In [15]:
df_product_category = pd.read_csv('data/product_category_name_translation.csv')
df_product_category.head()

product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [16]:
df_product_category.shape

(71, 2)

### Sellers Dataset

In [17]:
df_sellers = pd.read_csv('data/sellers_dataset.csv')
df_sellers.head()

seller_id  seller_zip_code_prefix  \
0  3442f8959a84dea7ee197c632cb2df15                   13023   
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844   
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031   
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195   
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914   

         seller_city seller_state  
0           campinas           SP  
1         mogi guacu           SP  
2     rio de janeiro           RJ  
3          sao paulo           SP  
4  braganca paulista           SP

In [18]:
df_sellers.shape

(3095, 4)

### Geolocation Dataset

In [19]:
df_geo = pd.read_csv('data/geolocation_dataset.csv')
df_geo.head()

geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292   
1                         1046       -23.546081       -46.644820   
2                         1046       -23.546129       -46.642951   
3                         1041       -23.544392       -46.639499   
4                         1035       -23.541578       -46.641607   

  geolocation_city geolocation_state  
0        sao paulo                SP  
1        sao paulo                SP  
2        sao paulo                SP  
3        sao paulo                SP  
4        sao paulo                SP

In [20]:
df_geo.shape

(1000163, 5)

# _Assessing Data_

## **Customer Dataset**

In [21]:
df_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64 
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB


Dapat dilihat bahwa dataset customer tidak memiliki null values dan terdiri dari 4 jenis data object dan 1 data int64

In [22]:
df_customer.describe()

customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [23]:
df_customer.isna().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

tidak ada missing value pada dataset customer

In [24]:
df_customer.duplicated().sum()

0

tidak ada nilai duplikat pada dataset customer

## **Order Dataset**

### df_order

In [25]:
df_order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype 
---  ------                         --------------  ----- 
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB


Terdapat beberapa missing values pada kolom order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, 

In [26]:
df_order.describe()

order_id                       customer_id  \
count                              99441                             99441   
unique                             99441                             99441   
top     e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d   
freq                                   1                                 1   

       order_status order_purchase_timestamp    order_approved_at  \
count         99441                    99441                99281   
unique            8                    98875                90733   
top       delivered      2018-04-11 10:48:14  2018-02-27 04:31:10   
freq          96478                        3                    9   

       order_delivered_carrier_date order_delivered_customer_date  \
count                         97658                         96476   
unique                        81018                         95664   
top             2018-05-09 15:48:00           2018-05-08 23:38:46   
freq                             47                             3   

       order_estimated_delivery_date  
count                          99441  
unique                           459  
top              2017-12-20 00:00:00  
freq                             522

In [27]:
df_order.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

terdapat banyak missing value pada feature 'order_approved_at' sebanyak 160 missing value, pada feature 'order_delivered_carrier_date' terdapat 1783 missing value, pada feature 'order_delivered_customer_date' terdapat 2965 missing value

In [28]:
df_order.duplicated().sum()

0

tidak terdapat duplicated value pada df_order

### df_order_items

In [29]:
df_order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   order_id             112650 non-null  object 
 1   order_item_id        112650 non-null  int64  
 2   product_id           112650 non-null  object 
 3   seller_id            112650 non-null  object 
 4   shipping_limit_date  112650 non-null  object 
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB


In [30]:
df_order_items.describe()

order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

In [31]:
df_order_items.isna().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

tidak ada missing value

In [32]:
df_order_items.duplicated().sum()

0

tidak ada duplicated value

### df_order_payments

In [33]:
df_order_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   order_id              103886 non-null  object 
 1   payment_sequential    103886 non-null  int64  
 2   payment_type          103886 non-null  object 
 3   payment_installments  103886 non-null  int64  
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB


In [34]:
df_order_payments.describe()

payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

In [35]:
df_order_payments.isna().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

tidak ada missing value

In [36]:
df_order_payments.duplicated().sum()

0

tidak ada duplicated value

### df_order_reviews

In [37]:
df_order_review.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64 
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB


Terdapat banyak sekali missing value pada feature review_comment_title dan review_comment_message.

In [38]:
df_order_review.describe()

review_score
count  99224.000000
mean       4.086421
std        1.347579
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

Dapat dilihat bahwa berarti skala nilai review berada di rentang 1 - 5 dengan rata - rata nilai review sebesar 4

In [39]:
df_order_review.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

terdapat banyak missing value pada feature 'review_comment_title' sebesar 87656 dan pada feature 'review_comment_message' sebesar 58247

In [40]:
df_order_review.duplicated().sum()

0

tidak ada duplicated value

### Labeling Order Delivery Status

In [41]:
# df_order_only =  df_orders.customer_id
df_order["delivery_status"] = np.where(df_order["order_estimated_delivery_date"] < df_order["order_delivered_customer_date"], 'Terlambat', 'Tepat Waktu')

In [42]:
df_order.head()

order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d   
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef   
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089   
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82   
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c   

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15   
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27   
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23   
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59   
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29   

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13   
1          2018-07-26 14:31:00           2018-08-07 15:27:45   
2          2018-08-08 13:50:00           2018-08-17 18:06:29   
3          2017-11-22 13:39:59           2017-12-02 00:28:42   
4          2018-02-14 19:46:34           2018-02-16 18:17:02   

  order_estimated_delivery_date delivery_status  
0           2017-10-18 00:00:00     Tepat Waktu  
1           2018-08-13 00:00:00     Tepat Waktu  
2           2018-09-04 00:00:00     Tepat Waktu  
3           2017-12-15 00:00:00     Tepat Waktu  
4           2018-02-26 00:00:00     Tepat Waktu

Memberikan label ke status pengiriman menjadi Tepat waktu dan Terlambat

## **Product Dataset**

### df_product

In [43]:
df_product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   product_id                  32951 non-null  object 
 1   product_category_name       32341 non-null  object 
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB


Terdapat indikasi missing value pada semua feature karena jumlah non null nya berbeda dengan product id

In [44]:
df_product.describe()

product_name_lenght  product_description_lenght  product_photos_qty  \
count         32341.000000                32341.000000        32341.000000   
mean             48.476949                  771.495285            2.188986   
std              10.245741                  635.115225            1.736766   
min               5.000000                    4.000000            1.000000   
25%              42.000000                  339.000000            1.000000   
50%              51.000000                  595.000000            1.000000   
75%              57.000000                  972.000000            3.000000   
max              76.000000                 3992.000000           20.000000   

       product_weight_g  product_length_cm  product_height_cm  \
count      32949.000000       32949.000000       32949.000000   
mean        2276.472488          30.815078          16.937661   
std         4282.038731          16.914458          13.637554   
min            0.000000           7.000000           2.000000   
25%          300.000000          18.000000           8.000000   
50%          700.000000          25.000000          13.000000   
75%         1900.000000          38.000000          21.000000   
max        40425.000000         105.000000         105.000000   

       product_width_cm  
count      32949.000000  
mean          23.196728  
std           12.079047  
min            6.000000  
25%           15.000000  
50%           20.000000  
75%           30.000000  
max          118.000000

In [45]:
df_product.isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Terdapat beberapa missing value pada semua feature yang jumlahnya tidak banyak

In [46]:
df_product.duplicated().sum()

0

tidak terdapat duplicated value

### df_products_category

In [47]:
df_product_category.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype 
---  ------                         --------------  ----- 
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB


In [48]:
df_product_category.describe()

product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

In [49]:
df_product_category.isna().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

tidak terdapat missing value

In [50]:
df_product_category.duplicated().sum()

0

tidak terdapat duplicated value

## **Sellers Dataset**

In [51]:
df_sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64 
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB


Tidak terdapat indikasi missing value pada dataset

In [52]:
df_sellers.describe()

seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000

In [53]:
df_sellers.isna().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

tidak ada missing value

In [54]:
df_sellers.duplicated().sum()

0

tidak ada duplicated value

## Geolocation Dataset

In [55]:
df_geo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype  
---  ------                       --------------    -----  
 0   geolocation_zip_code_prefix  1000163 non-null  int64  
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object 
 4   geolocation_state            1000163 non-null  object 
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB


In [56]:
df_geo.isna().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

tidak ada missing value

In [57]:
df_geo.duplicated().sum()

261831

terdapat banyak sekali duplicated value, namun mengingat ini adalah data lokasi, maka wajar saja ada beberapa data yang sama karena mengindikasikan letak pelanggan yang ada pada daerah tertentu dan berada pada daerah yang sama

# _CLEANING DATA_

## **Order Dataset**

### **df_order**

#### MENGUBAH DATETIME

In [58]:
df_order.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
delivery_status                     0
dtype: int64

In [59]:
datetime_columns = ["order_approved_at","order_delivered_carrier_date",'order_delivered_customer_date','order_estimated_delivery_date']
 
for column in datetime_columns:
  df_order[column] = pd.to_datetime(df_order[column])
  df_order[column] = df_order[column].dt.date
  df_order[column] = pd.to_datetime(df_order[column])
df_order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype         
---  ------                         --------------  -----         
 0   order_id                       99441 non-null  object        
 1   customer_id                    99441 non-null  object        
 2   order_status                   99441 non-null  object        
 3   order_purchase_timestamp       99441 non-null  object        
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
 8   delivery_status                99441 non-null  object        
dtypes: datetime64[ns](4), object(5)
memory usage: 6.8+ MB


Mengubah feature yang memiliki tipe data waktu menjadi tipe data datetime64

In [60]:
datetime_columns = ["order_purchase_timestamp"]
 
for column in datetime_columns:
  df_order[column] = pd.to_datetime(df_order[column])
  df_order[column] = df_order[column].dt.strftime("%H")
df_order.head()

order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d   
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef   
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089   
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82   
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c   

  order_status order_purchase_timestamp order_approved_at  \
0    delivered                       10        2017-10-02   
1    delivered                       20        2018-07-26   
2    delivered                       08        2018-08-08   
3    delivered                       19        2017-11-18   
4    delivered                       21        2018-02-13   

  order_delivered_carrier_date order_delivered_customer_date  \
0                   2017-10-04                    2017-10-10   
1                   2018-07-26                    2018-08-07   
2                   2018-08-08                    2018-08-17   
3                   2017-11-22                    2017-12-02   
4                   2018-02-14                    2018-02-16   

  order_estimated_delivery_date delivery_status  
0                    2017-10-18     Tepat Waktu  
1                    2018-08-13     Tepat Waktu  
2                    2018-09-04     Tepat Waktu  
3                    2017-12-15     Tepat Waktu  
4                    2018-02-26     Tepat Waktu

Mengubah order_purchase_timestamp menjadi format waktu dalam jam dan tipe data int bukan date time sehingga bisa di beri label

#### HANDLING MISSING VALUE

In [61]:
df_order[df_order.order_approved_at.isna()]

order_id                       customer_id  \
1130   00b1cb0320190ca0daa2c88b35206009  3532ba38a3fd242259a514ac2b6ae6b6   
1801   ed3efbd3a87bea76c2812c66a0b32219  191984a8ba4cbb2145acb4fe35b69664   
1868   df8282afe61008dc26c6c31011474d02  aa797b187b5466bc6925aaaa4bb3bed1   
2029   8d4c637f1accf7a88a4555f02741e606  b1dd715db389a2077f43174e7a675d07   
2161   7a9d4c7f9b068337875b95465330f2fc  7f71ae48074c0cfec9195f88fcbfac55   
...                                 ...                               ...   
97696  5a00b4d35edffc56b825c3646a99ba9d  6a3bdf004ca96338fb5fad1b8d93c2e6   
98415  227c804e2a44760671a6a5697ea549e4  62e7477e75e542243ee62a0ba73f410f   
98909  e49e7ce1471b4693482d40c2bd3ad196  e4e7ab3f449aeb401f0216f86c2104db   
99283  3a3cddda5a7c27851bd96c3313412840  0b0d6095c5555fe083844281f6b093bb   
99347  a89abace0dcc01eeb267a9660b5ac126  2f0524a7b1b3845a1a57fcf3910c4333   

      order_status order_purchase_timestamp order_approved_at  \
1130      canceled                       15               NaT   
1801      canceled                       13               NaT   
1868      canceled                       12               NaT   
2029      canceled                       16               NaT   
2161      canceled                       16               NaT   
...            ...                      ...               ...   
97696     canceled                       15               NaT   
98415     canceled                       15               NaT   
98909     canceled                       11               NaT   
99283     canceled                       16               NaT   
99347     canceled                       18               NaT   

      order_delivered_carrier_date order_delivered_customer_date  \
1130                           NaT                           NaT   
1801                           NaT                           NaT   
1868                           NaT                           NaT   
2029                           NaT                           NaT   
2161                           NaT                           NaT   
...                            ...                           ...   
97696                          NaT                           NaT   
98415                          NaT                           NaT   
98909                          NaT                           NaT   
99283                          NaT                           NaT   
99347                          NaT                           NaT   

      order_estimated_delivery_date delivery_status  
1130                     2018-09-12     Tepat Waktu  
1801                     2018-10-17     Tepat Waktu  
1868                     2017-04-10     Tepat Waktu  
2029                     2018-09-13     Tepat Waktu  
2161                     2017-05-30     Tepat Waktu  
...                             ...             ...  
97696                    2017-07-25     Tepat Waktu  
98415                    2017-10-16     Tepat Waktu  
98909                    2018-08-10     Tepat Waktu  
99283                    2018-10-01     Tepat Waktu  
99347                    2018-09-27     Tepat Waktu  

[160 rows x 9 columns]

Terlihat bahwa missing value yang dimiliki ketiga feature order_approved_at, order_delivered_carrier_date, order_delivered_customer_date selalu berpasangan

In [62]:
df_order = df_order.sort_values('order_approved_at')

Melakukan sort values pada feature order_approved_at agar tersusun sesuai tanggal

In [63]:
df_order['order_approved_at'] = df_order['order_approved_at'].fillna(method='ffill')

Melakukan forward fill untuk mengisi nilai missing value pada feature order_approved_at

In [64]:
df_order = df_order.sort_values('order_delivered_carrier_date')

Melakukan sort values pada feature order_delivered_carrier_date agar tersusun sesuai tanggal

In [65]:
df_order['order_delivered_carrier_date'] = df_order['order_delivered_carrier_date'].fillna(method='ffill')

Melakukan forward fill untuk mengisi nilai missing value pada feature order_delivered_carrier_date

In [66]:
df_order = df_order.sort_values('order_delivered_customer_date')

Melakukan sort values pada feature order_delivered_customer_date agar tersusun sesuai tanggal

In [67]:
df_order['order_delivered_customer_date'] = df_order['order_delivered_customer_date'].fillna(method='ffill')

Melakukan forward fill untuk mengisi nilai missing value pada feature order_delivered_carrier_date

In [68]:
df_order.isna().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
delivery_status                  0
dtype: int64

Sehingga missing value berhasil untuk diatasi dan dataset sudah tidak memiliki missing value 

### **df_order_review**

In [69]:
df_order_review[df_order_review.review_comment_title.isna()]

review_id                          order_id  \
0      7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb   
1      80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33   
2      228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b   
3      e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b   
4      f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1   
...                                 ...                               ...   
99219  574ed12dd733e5fa530cfd4bbf39d7c9  2a8c23fee101d4d5662fa670396eb8da   
99220  f3897127253a9592a73be9bdfdf4ed7a  22ec9f0669f784db00fa86d035cf8602   
99221  b3de70c89b1510c4cd3d0649fd302472  55d4004744368f5571d1f590031933e4   
99222  1adeb9d84d72fe4e337617733eb85149  7725825d039fc1f0ceb7635e3f7d9206   
99223  efe49f1d6f951dd88b51e6ccd4cc548f  90531360ecb1eec2a1fbb265a0db0508   

       review_score review_comment_title  \
0                 4                  NaN   
1                 5                  NaN   
2                 5                  NaN   
3                 5                  NaN   
4                 5                  NaN   
...             ...                  ...   
99219             5                  NaN   
99220             5                  NaN   
99221             5                  NaN   
99222             4                  NaN   
99223             1                  NaN   

                                  review_comment_message review_creation_date  \
0                                                    NaN  2018-01-18 00:00:00   
1                                                    NaN  2018-03-10 00:00:00   
2                                                    NaN  2018-02-17 00:00:00   
3                  Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00   
4      Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00   
...                                                  ...                  ...   
99219                                                NaN  2018-07-07 00:00:00   
99220                                                NaN  2017-12-09 00:00:00   
99221  Excelente mochila, entrega super rápida. Super...  2018-03-22 00:00:00   
99222                                                NaN  2018-07-01 00:00:00   
99223  meu produto chegou e ja tenho que devolver, po...  2017-07-03 00:00:00   

      review_answer_timestamp  
0         2018-01-18 21:46:59  
1         2018-03-11 03:05:13  
2         2018-02-18 14:36:24  
3         2017-04-21 22:02:06  
4         2018-03-02 10:26:53  
...                       ...  
99219     2018-07-14 17:18:30  
99220     2017-12-11 20:06:42  
99221     2018-03-23 09:10:43  
99222     2018-07-02 12:59:13  
99223     2017-07-03 21:01:49  

[87656 rows x 7 columns]

Terlihat bahwa banyak sekali review dari pelanggan yang tidak mencantukman judul reviewnya

In [70]:
df_order_review[df_order_review.review_comment_message.isna()]

review_id                          order_id  \
0      7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb   
1      80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33   
2      228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b   
5      15197aa66ff4d0650b5434f1b46cda19  b18dcdf73be66366873cd26c5724d1dc   
6      07f9bee5d1b850860defd761afa7ff16  e48aa0d2dcec3a2e87348811bcfdf22b   
...                                 ...                               ...   
99217  c6b270c61f67c9f7cb07d84ea8aeaf8b  48f7ee67313eda32bfcf5b9c1dd9522d   
99218  af2dc0519de6e0720ef0c74292fb4114  d699c734a0b1c8111f2272a3f36d398c   
99219  574ed12dd733e5fa530cfd4bbf39d7c9  2a8c23fee101d4d5662fa670396eb8da   
99220  f3897127253a9592a73be9bdfdf4ed7a  22ec9f0669f784db00fa86d035cf8602   
99222  1adeb9d84d72fe4e337617733eb85149  7725825d039fc1f0ceb7635e3f7d9206   

       review_score review_comment_title review_comment_message  \
0                 4                  NaN                    NaN   
1                 5                  NaN                    NaN   
2                 5                  NaN                    NaN   
5                 1                  NaN                    NaN   
6                 5                  NaN                    NaN   
...             ...                  ...                    ...   
99217             5                  NaN                    NaN   
99218             5                  NaN                    NaN   
99219             5                  NaN                    NaN   
99220             5                  NaN                    NaN   
99222             4                  NaN                    NaN   

      review_creation_date review_answer_timestamp  
0      2018-01-18 00:00:00     2018-01-18 21:46:59  
1      2018-03-10 00:00:00     2018-03-11 03:05:13  
2      2018-02-17 00:00:00     2018-02-18 14:36:24  
5      2018-04-13 00:00:00     2018-04-16 00:39:37  
6      2017-07-16 00:00:00     2017-07-18 19:30:34  
...                    ...                     ...  
99217  2017-12-13 00:00:00     2017-12-14 11:09:36  
99218  2018-04-27 00:00:00     2018-04-30 01:18:57  
99219  2018-07-07 00:00:00     2018-07-14 17:18:30  
99220  2017-12-09 00:00:00     2017-12-11 20:06:42  
99222  2018-07-01 00:00:00     2018-07-02 12:59:13  

[58247 rows x 7 columns]

Terlihat bahwa review yang bernilai null maka title reviewnya juga bernilai null

In [71]:
df_order_review_clean = df_order_review.drop(['review_comment_title', 'review_comment_message'], axis=1)

Karena terlalu banyak nilai missing value nya maka dilakukan drop kepada kedua feature tersebut

In [72]:
datetime_columns = ["review_creation_date"]
 
for column in datetime_columns:
  df_order_review_clean[column] = pd.to_datetime(df_order_review_clean[column])
  df_order_review_clean[column] = df_order_review_clean[column].dt.date
  df_order_review_clean[column] = pd.to_datetime(df_order_review_clean[column])
df_order_review_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype         
---  ------                   --------------  -----         
 0   review_id                99224 non-null  object        
 1   order_id                 99224 non-null  object        
 2   review_score             99224 non-null  int64         
 3   review_creation_date     99224 non-null  datetime64[ns]
 4   review_answer_timestamp  99224 non-null  object        
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 3.8+ MB


Mengubah feature review_creation_date agar bertipe data datetime64

In [73]:
datetime_columns = ["review_answer_timestamp"]
 
for column in datetime_columns:
  df_order_review_clean[column] = pd.to_datetime(df_order_review_clean[column])
  df_order_review_clean[column] = df_order_review_clean[column].dt.strftime("%H")
df_order_review_clean.head()

review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb   
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33   
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b   
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b   
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1   

   review_score review_creation_date review_answer_timestamp  
0             4           2018-01-18                      21  
1             5           2018-03-10                      03  
2             5           2018-02-17                      14  
3             5           2017-04-21                      22  
4             5           2018-03-01                      10

Mengubah format datetime review_creation_date kedalam bentuk jam

### Combine Data Order

In [74]:
df_orders_1 = pd.merge(
    left=df_order,
    right=df_order_items,
    how="inner",
    left_on="order_id",
    right_on="order_id"
)
df_orders_2 = pd.merge(
    left=df_orders_1,
    right=df_order_payments,
    how="inner",
    left_on="order_id",
    right_on="order_id"
)
df_orders = pd.merge(
    left=df_orders_2,
    right=df_order_review_clean,
    how="inner",
    left_on="order_id",
    right_on="order_id"
)

df_orders.head()


order_id                       customer_id  \
0  36989eb07a0de2d3d3129eea35553875  aadd27185177fc7ac9b364898ac09343   
1  36989eb07a0de2d3d3129eea35553875  aadd27185177fc7ac9b364898ac09343   
2  7033745709b7cf1bac7d2533663592de  7f0ca17bb33b230b47459437cf0682c7   
3  5204d67853f827d1ee32810bf8f2d6c2  3dc7eb6da6c008460353d9a171e8fe6d   
4  5204d67853f827d1ee32810bf8f2d6c2  3dc7eb6da6c008460353d9a171e8fe6d   

  order_status order_purchase_timestamp order_approved_at  \
0    delivered                       13        2016-10-04   
1    delivered                       13        2016-10-04   
2    delivered                       14        2016-10-04   
3    delivered                       17        2016-10-06   
4    delivered                       17        2016-10-06   

  order_delivered_carrier_date order_delivered_customer_date  \
0                   2016-10-08                    2016-10-11   
1                   2016-10-08                    2016-10-11   
2                   2016-10-08                    2016-10-11   
3                   2016-10-10                    2016-10-13   
4                   2016-10-10                    2016-10-13   

  order_estimated_delivery_date delivery_status  order_item_id  \
0                    2016-12-06     Tepat Waktu              1   
1                    2016-12-06     Tepat Waktu              2   
2                    2016-11-30     Tepat Waktu              1   
3                    2016-11-28     Tepat Waktu              1   
4                    2016-11-28     Tepat Waktu              1   

                         product_id                         seller_id  \
0  43bb8825dd6838251606e5e4130cfff4  939f6e231201f26803cb5c3a3d2940b3   
1  43bb8825dd6838251606e5e4130cfff4  939f6e231201f26803cb5c3a3d2940b3   
2  35084deab9603bbb6035bb8638b1df89  df560393f3a51e74553ab94004ba5c87   
3  b6f134ff2933bb0ee1f36e2865f21a91  0c8380b62e38e8a1e6adbeba7eb9688c   
4  b6f134ff2933bb0ee1f36e2865f21a91  0c8380b62e38e8a1e6adbeba7eb9688c   

   shipping_limit_date  price  freight_value  payment_sequential payment_type  \
0  2016-10-08 13:46:32   23.9          26.82                   1  credit_card   
1  2016-10-08 13:46:32   23.9          26.82                   1  credit_card   
2  2016-10-08 14:46:49   93.9          17.61                   1  credit_card   
3  2016-10-10 15:45:44  139.9          21.34                   2      voucher   
4  2016-10-10 15:45:44  139.9          21.34                   1  credit_card   

   payment_installments  payment_value                         review_id  \
0                    10         101.44  7d58a5b4bc501c1ece8972fa04351be2   
1                    10         101.44  7d58a5b4bc501c1ece8972fa04351be2   
2                     4         111.51  a0ba97ce98f76cf57bb2c5530513be70   
3                     1          74.65  faf9ce3802b882a10bcd548f421ea9ff   
4                     3          86.59  faf9ce3802b882a10bcd548f421ea9ff   

   review_score review_creation_date review_answer_timestamp  
0             5           2016-10-20                      01  
1             5           2016-10-20                      01  
2             3           2016-10-25                      23  
3             5           2016-10-18                      19  
4             5           2016-10-18                      19

Menggabungkan semua dataset order menjadi satu dataset

In [75]:
df_orders.isna().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
delivery_status                  0
order_item_id                    0
product_id                       0
seller_id                        0
shipping_limit_date              0
price                            0
freight_value                    0
payment_sequential               0
payment_type                     0
payment_installments             0
payment_value                    0
review_id                        0
review_score                     0
review_creation_date             0
review_answer_timestamp          0
dtype: int64

sudah tidak ada lagi missing value pada dataset order

In [76]:
df_orders.shape

(117329, 23)

## Products Dataset

### df_product

In [77]:
df_product.shape

(32951, 9)

In [78]:
df_product.isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

terdapat beberapa missing value

In [79]:
df_product[df_product.product_category_name.isna()]

product_id product_category_name  \
105    a41e356c76fab66334f36de622ecbd3a                   NaN   
128    d8dee61c2034d6d075997acef1870e9b                   NaN   
145    56139431d72cd51f19eb9f7dae4d1617                   NaN   
154    46b48281eb6d663ced748f324108c733                   NaN   
197    5fb61f482620cb672f5e586bb132eae9                   NaN   
...                                 ...                   ...   
32515  b0a0c5dd78e644373b199380612c350a                   NaN   
32589  10dbe0fbaa2c505123c17fdc34a63c56                   NaN   
32616  bd2ada37b58ae94cc838b9c0569fecd8                   NaN   
32772  fa51e914046aab32764c41356b9d4ea4                   NaN   
32852  c4ceee876c82b8328e9c293fa0e1989b                   NaN   

       product_name_lenght  product_description_lenght  product_photos_qty  \
105                    NaN                         NaN                 NaN   
128                    NaN                         NaN                 NaN   
145                    NaN                         NaN                 NaN   
154                    NaN                         NaN                 NaN   
197                    NaN                         NaN                 NaN   
...                    ...                         ...                 ...   
32515                  NaN                         NaN                 NaN   
32589                  NaN                         NaN                 NaN   
32616                  NaN                         NaN                 NaN   
32772                  NaN                         NaN                 NaN   
32852                  NaN                         NaN                 NaN   

       product_weight_g  product_length_cm  product_height_cm  \
105               650.0               17.0               14.0   
128               300.0               16.0                7.0   
145               200.0               20.0               20.0   
154             18500.0               41.0               30.0   
197               300.0               35.0                7.0   
...                 ...                ...                ...   
32515            1800.0               30.0               20.0   
32589             800.0               30.0               10.0   
32616             200.0               21.0                8.0   
32772            1300.0               45.0               16.0   
32852             700.0               28.0                3.0   

       product_width_cm  
105                12.0  
128                20.0  
145                20.0  
154                41.0  
197                12.0  
...                 ...  
32515              70.0  
32589              23.0  
32616              16.0  
32772              45.0  
32852              43.0  

[610 rows x 9 columns]

nilai missing value product_category_name selalu bergandengan dengan mising value ketiga kolom lainnya yaitu 'product_name_lenght', 'product_description_lenght', 'product_photos_qty'

karena missing value yang ada sedikit dan juga tidak terlalu mempengaruhi visualiasi maka kita akan drop missing value

In [80]:
df_product_clean = df_product.dropna()

In [81]:
df_product_clean.isna().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

### Combine Data Product

In [82]:
df_products = pd.merge(
    left=df_product_clean,
    right=df_product_category,
    how="inner",
    left_on="product_category_name",
    right_on="product_category_name"
)
df_products.head()

product_id product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5            perfumaria   
1  6a2fb4dd53d2cdb88e0432f1284a004c            perfumaria   
2  0d009643171aee696f4733340bc2fdd0            perfumaria   
3  b1eae565a61935e0011ee7682fef9dc9            perfumaria   
4  8da90b37f0fb171b4877c124f965b1f6            perfumaria   

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0   
1                 39.0                       346.0                 2.0   
2                 52.0                       150.0                 1.0   
3                 49.0                       460.0                 2.0   
4                 56.0                       733.0                 3.0   

   product_weight_g  product_length_cm  product_height_cm  product_width_cm  \
0             225.0               16.0               10.0              14.0   
1             400.0               27.0                5.0              20.0   
2             422.0               21.0               16.0              18.0   
3             267.0               17.0               13.0              17.0   
4             377.0               18.0               13.0              15.0   

  product_category_name_english  
0                     perfumery  
1                     perfumery  
2                     perfumery  
3                     perfumery  
4                     perfumery

Menggabungkan semua data produk menjadi satu dataset

In [83]:
df_products.isna().sum()

product_id                       0
product_category_name            0
product_name_lenght              0
product_description_lenght       0
product_photos_qty               0
product_weight_g                 0
product_length_cm                0
product_height_cm                0
product_width_cm                 0
product_category_name_english    0
dtype: int64

In [84]:
df_products.shape

(32327, 10)

# Exploratory Data Analysis

### Dari dataset yang sudah diolah dapat dilakukan beberapa analasis tentang hal - hal berikut,

Sales Analysis :
- Bagaimana tingkat penjualan dan pendapatan pada tahun 2016 ?
- Bagaimana tingkat penjualan dan pendapatan pada tahun 2017 ?
- Bagaimana tingkat penjualan dan pendapatan pada tahun 2018 ?

Product Analysis :
- Apa saja 10 produk yang memiliki tingkat penjualan paling tinggi ?
- Apa saja 10 produk yang memiliki tingkat penjualan paling rendah ?

Customer and Seller Analysis :
- Bagaimana pesebaran daerah dari pelanggan yang melakukan transaksi ?
- Bagaimana pesebaran daerah dari penjual yang melakukan transaksi ?
- Bagaimana Analisis tingkat RFM dari pelanggan yang ada ?
- Bagaimana segmentasi pelanggan yang didapatkan dari hasil analisis RFM ?

Order and Purchase Analysis :
- Berapa banyak pesanan yang sampai dengan tepat waktu kepada pelanggan?
- Berapa banyak pesanan yang sampai terlambat kepada pelanggan ?
- Apa jenis pembayaran yang paling banyak digunakan oleh pelanggan ?
- Kapan waktu yang paling banyak terjadi transaksi oleh pelanggan ?

## Data Customer

In [85]:
df_customer.head()

customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0   
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3   
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e   
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c   
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066   

   customer_zip_code_prefix          customer_city customer_state  
0                     14409                 franca             SP  
1                      9790  sao bernardo do campo             SP  
2                      1151              sao paulo             SP  
3                      8775        mogi das cruzes             SP  
4                     13056               campinas             SP

In [86]:
df_customer.groupby(by="customer_state").agg({
    "customer_id": "nunique",
    "customer_city" : "unique"
}).sort_values(by="customer_id",ascending=False).reset_index()

customer_state  customer_id  \
0              SP        41746   
1              RJ        12852   
2              MG        11635   
3              RS         5466   
4              PR         5045   
5              SC         3637   
6              BA         3380   
7              DF         2140   
8              ES         2033   
9              GO         2020   
10             PE         1652   
11             CE         1336   
12             PA          975   
13             MT          907   
14             MA          747   
15             MS          715   
16             PB          536   
17             PI          495   
18             RN          485   
19             AL          413   
20             SE          350   
21             TO          280   
22             RO          253   
23             AM          148   
24             AC           81   
25             AP           68   
26             RR           46   

                                        customer_city  
0   [franca, sao bernardo do campo, sao paulo, mog...  
1   [rio de janeiro, resende, parati, sao goncalo,...  
2   [timoteo, belo horizonte, montes claros, santa...  
3   [caxias do sul, novo hamburgo, pelotas, porto ...  
4   [curitiba, sao jose dos pinhais, cascavel, ara...  
5   [jaragua do sul, florianopolis, sao jose, timb...  
6   [camacari, cruz das almas, feira de santana, s...  
7   [brasilia, taguatinga, sobradinho, guara, ceil...  
8   [cachoeiro de itapemirim, ibatiba, vila velha,...  
9   [aparecida de goiania, goiania, trindade, bom ...  
10  [paulista, recife, jaboatao dos guararapes, li...  
11  [fortaleza, sobral, itapiuna, taperuaba, forqu...  
12  [pacaja, belem, altamira, castanhal, dom elise...  
13  [barra do garcas, sinop, alta floresta, aripua...  
14  [sao luis, vargem grande, coelho neto, balsas,...  
15  [dourados, rio brilhante, ponta pora, tres lag...  
16  [campina grande, joao pessoa, soledade, banane...  
17  [teresina, picos, regeneracao, buriti dos lope...  
18  [areia branca, natal, parnamirim, pedro velho,...  
19  [maceio, arapiraca, cajueiro, canapi, palmeira...  
20  [aracaju, itabaianinha, sao miguel do aleixo, ...  
21  [gurupi, taguatinga, palmas, ananas, sandoland...  
22  [espigao do oeste, ariquemes, sao francisco do...  
23  [manaus, urucurituba, humaita, itacoatiara, co...  
24  [rio branco, senador guiomard, cruzeiro do sul...  
25  [macapa, santana, vitoria do jari, oiapoque, p...  
26                                [boa vista, bonfim]

Dapat dilihat bahwa state SP memiliki jumlah customer terbanyak

In [87]:
df_customer.groupby(by="customer_city").agg({
    "customer_id": "nunique"
}).sort_values(by="customer_id",ascending=False).reset_index().nlargest(10, "customer_id")

customer_city  customer_id
0              sao paulo        15540
1         rio de janeiro         6882
2         belo horizonte         2773
3               brasilia         2131
4               curitiba         1521
5               campinas         1444
6           porto alegre         1379
7               salvador         1245
8              guarulhos         1189
9  sao bernardo do campo          938

Dapat dilihat bahwa kota sao paulo memiliki jumlah customer terbanyak

In [88]:
df_customer.groupby(by="customer_city").agg({
    "customer_id": "nunique"
}).sort_values(by="customer_id",ascending=False).reset_index().nsmallest(10, "customer_id")

customer_city  customer_id
2975               acucena            1
2976           sao nicolau            1
2977           alexandrita            1
2978  sao miguel do cambui            1
2979               trabiju            1
2980               caxingo            1
2981               vieiras            1
2982        caxambu do sul            1
2983     alfredo marcondes            1
2984              cotipora            1

Dapat dilihat bahwa kota acucena hingga cotipora memiliki jumlah customer paling sedikit yaitu 1

## Data Orders

In [89]:
df_orders.head()

order_id                       customer_id  \
0  36989eb07a0de2d3d3129eea35553875  aadd27185177fc7ac9b364898ac09343   
1  36989eb07a0de2d3d3129eea35553875  aadd27185177fc7ac9b364898ac09343   
2  7033745709b7cf1bac7d2533663592de  7f0ca17bb33b230b47459437cf0682c7   
3  5204d67853f827d1ee32810bf8f2d6c2  3dc7eb6da6c008460353d9a171e8fe6d   
4  5204d67853f827d1ee32810bf8f2d6c2  3dc7eb6da6c008460353d9a171e8fe6d   

  order_status order_purchase_timestamp order_approved_at  \
0    delivered                       13        2016-10-04   
1    delivered                       13        2016-10-04   
2    delivered                       14        2016-10-04   
3    delivered                       17        2016-10-06   
4    delivered                       17        2016-10-06   

  order_delivered_carrier_date order_delivered_customer_date  \
0                   2016-10-08                    2016-10-11   
1                   2016-10-08                    2016-10-11   
2                   2016-10-08                    2016-10-11   
3                   2016-10-10                    2016-10-13   
4                   2016-10-10                    2016-10-13   

  order_estimated_delivery_date delivery_status  order_item_id  \
0                    2016-12-06     Tepat Waktu              1   
1                    2016-12-06     Tepat Waktu              2   
2                    2016-11-30     Tepat Waktu              1   
3                    2016-11-28     Tepat Waktu              1   
4                    2016-11-28     Tepat Waktu              1   

                         product_id                         seller_id  \
0  43bb8825dd6838251606e5e4130cfff4  939f6e231201f26803cb5c3a3d2940b3   
1  43bb8825dd6838251606e5e4130cfff4  939f6e231201f26803cb5c3a3d2940b3   
2  35084deab9603bbb6035bb8638b1df89  df560393f3a51e74553ab94004ba5c87   
3  b6f134ff2933bb0ee1f36e2865f21a91  0c8380b62e38e8a1e6adbeba7eb9688c   
4  b6f134ff2933bb0ee1f36e2865f21a91  0c8380b62e38e8a1e6adbeba7eb9688c   

   shipping_limit_date  price  freight_value  payment_sequential payment_type  \
0  2016-10-08 13:46:32   23.9          26.82                   1  credit_card   
1  2016-10-08 13:46:32   23.9          26.82                   1  credit_card   
2  2016-10-08 14:46:49   93.9          17.61                   1  credit_card   
3  2016-10-10 15:45:44  139.9          21.34                   2      voucher   
4  2016-10-10 15:45:44  139.9          21.34                   1  credit_card   

   payment_installments  payment_value                         review_id  \
0                    10         101.44  7d58a5b4bc501c1ece8972fa04351be2   
1                    10         101.44  7d58a5b4bc501c1ece8972fa04351be2   
2                     4         111.51  a0ba97ce98f76cf57bb2c5530513be70   
3                     1          74.65  faf9ce3802b882a10bcd548f421ea9ff   
4                     3          86.59  faf9ce3802b882a10bcd548f421ea9ff   

   review_score review_creation_date review_answer_timestamp  
0             5           2016-10-20                      01  
1             5           2016-10-20                      01  
2             3           2016-10-25                      23  
3             5           2016-10-18                      19  
4             5           2016-10-18                      19

In [90]:
df_orders.groupby(by="order_status").agg({
    "customer_id": "nunique"
}).sort_values(by="customer_id",ascending=False).reset_index()

order_status  customer_id
0    delivered        95831
1      shipped         1031
2     canceled          444
3     invoiced          307
4   processing          295
5  unavailable            6
6     approved            2

Terlihat bahwa 95831 barang yang sudah berhasil terkirim ke customer dan terdapat 444 barang yang di cancel transaksinya

In [91]:
df_orders[df_orders['order_estimated_delivery_date'] < df_orders['order_delivered_customer_date']]['review_score'].value_counts()

review_score
1    5741
5    1430
3     970
4     873
2     822
Name: count, dtype: int64

pengiriman yang terlambat mendapat banyak bintang 1 dari pelanggan

In [92]:
df_orders[df_orders['order_estimated_delivery_date'] > df_orders['order_delivered_customer_date']]['review_score'].value_counts()

review_score
5    64089
4    21068
1     8965
3     8670
2     3206
Name: count, dtype: int64

pengiriman yang tepat waktu mendapat banyak bintang 5 dari pelanggan

In [93]:
df_orders.groupby(by="payment_type").agg({
    "customer_id": "nunique",
    'payment_value': "mean"
}).sort_values(by="customer_id",ascending=False).reset_index()

payment_type  customer_id  payment_value
0  credit_card        75408     179.011599
1       boleto        19471     177.022206
2      voucher         3731      64.248868
3   debit_card         1514     150.077825

credit_card memiliki payment value paling besar karena banyak pelanggan yang menggunakan credit_card

In [94]:
df_orders['order_year'] = df_orders['order_approved_at'].dt.year
df_orders['order_month'] = df_orders['order_approved_at'].dt.month

membuat feature order_year dan order_month berdasarkan order_approved_at

In [95]:
def get_month_name(month):
    return (
        "january" if month == 1
        else
        "february" if month == 2
        else
        "march" if month == 3
        else
        "april" if month == 4
        else
        "may" if month == 5
        else
        "june" if month == 6
        else
        "july" if month == 7
        else
        "august" if month == 8
        else
        "september" if month == 9
        else
        "october" if month == 10
        else
        "november" if month == 11
        else
        "desember"
    )

In [96]:
df_orders['order_month_name'] = df_orders['order_month'].astype('int').map(get_month_name)

In [97]:
df_orders[['order_year','order_month_name']].head()

order_year order_month_name
0        2016          october
1        2016          october
2        2016          october
3        2016          october
4        2016          october

Memberi label bulan untuk tiap order

In [98]:
df_orders.order_month_name.unique()

array(['october', 'desember', 'january', 'september', 'february', 'march',
       'april', 'may', 'june', 'july', 'august', 'november'], dtype=object)

bisa dilihat kalau data e-commerce memiliki data yang lengkap mulai dari bulan januari hingga desembar

In [99]:
df_orders.order_year.unique()

array([2016, 2017, 2018])

data ini berisikan transaksi dari tahun 2016 hingga 2018

In [100]:
df_orders.groupby(by='order_month_name').agg({
    "customer_id": "nunique"
}).sort_values(by="customer_id",ascending=False).reset_index()

order_month_name  customer_id
0            august        10866
1               may        10636
2              july        10006
3             march         9835
4              june         9335
5             april         9068
6          february         8326
7           january         7817
8          november         7248
9          desember         5733
10          october         4801
11        september         4245

Bulan agustus menjadi bulan yang memiliki transaksi paling banyak

In [101]:
def get_part_of_day(hour):
    return (
        "morning" if 5 <= hour <= 11
        else
        "afternoon" if 12 <= hour <= 17
        else
        "evening" if 18 <= hour <= 22
        else
        "night"
    )

In [102]:
df_orders['order_purchase_time'] = df_orders['order_purchase_timestamp'].astype('int').map(get_part_of_day)
df_orders['review_answer_time'] = df_orders["review_answer_timestamp"].astype('int').map(get_part_of_day)

In [103]:
df_orders[['order_purchase_time','review_answer_time']].head()

order_purchase_time review_answer_time
0           afternoon              night
1           afternoon              night
2           afternoon              night
3           afternoon            evening
4           afternoon            evening

Memberi label waktu transaksi pelanggan

In [104]:
df_orders.groupby(by="order_purchase_time").agg({
    "customer_id": "nunique"
}).sort_values(by="customer_id",ascending=False).reset_index()

order_purchase_time  customer_id
0           afternoon        37780
1             evening        29532
2             morning        22083
3               night         8521

Terlihat bahwa transaksi pelanggan paling banyak dilakukan pada waktu siang hari

In [105]:
df_orders.groupby(by='review_answer_time').agg({
    "customer_id": "nunique"
}).sort_values(by="customer_id",ascending=False).reset_index()

review_answer_time  customer_id
0          afternoon        29100
1              night        26227
2            evening        26007
3            morning        16839

Terlihat bahwa sebagian besar pelanggan memberikan review di waktu siang hari

## Sellers

In [106]:
df_sellers.head()

seller_id  seller_zip_code_prefix  \
0  3442f8959a84dea7ee197c632cb2df15                   13023   
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844   
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031   
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195   
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914   

         seller_city seller_state  
0           campinas           SP  
1         mogi guacu           SP  
2     rio de janeiro           RJ  
3          sao paulo           SP  
4  braganca paulista           SP

In [107]:
df_sellers.groupby(by="seller_state").agg({
    "seller_id": "nunique",
    "seller_city" : "unique"
}).sort_values(by="seller_id",ascending=False).reset_index()

seller_state  seller_id                                        seller_city
0            SP       1849  [campinas, mogi guacu, sao paulo, braganca pau...
1            PR        349  [curitiba, arapongas, sao jose dos pinhais, po...
2            MG        244  [belo horizonte, camanducaia, congonhal, aragu...
3            SC        190  [tubarao, imbituba, garopaba, sao ludgero, sao...
4            RJ        171  [rio de janeiro, saquarema, petropolis, itabor...
5            RS        129  [tres de maio, porto alegre, santo antonio da ...
6            GO         40  [anapolis, santa terezinha de goias, uruacu, g...
7            DF         30                      [brasilia, brasilia df, gama]
8            ES         23  [viana, cachoeiro de itapemirim, cariacica / e...
9            BA         19  [lauro de freitas, porto seguro, salvador, bar...
10           CE         13  [fortaleza, mucambo, pacatuba, juzeiro do nort...
11           PE          9  [brejao, caruaru, recife, vitoria de santo antao]
12           PB          6  [mamanguape, campina grande, joao pessoa, serr...
13           MS          5                              [campo grande, coxim]
14           RN          5  [rio de janeiro, messias targino, parnamirim, ...
15           MT          4                           [cuiaba, jaciara, sinop]
16           RO          2                           [porto velho, ji parana]
17           SE          2                                [aracaju, neopolis]
18           AC          1                                       [rio branco]
19           PI          1                                         [teresina]
20           AM          1                                           [manaus]
21           MA          1                                         [sao luis]
22           PA          1                          [marechal candido rondon]

Seller terbanyak berada pada state SP

In [108]:
df_sellers.groupby(by="seller_city").agg({
    "seller_id": "nunique"
}).sort_values(by="seller_id",ascending=False).reset_index().nlargest(10, "seller_id")

seller_city  seller_id
0       sao paulo        694
1        curitiba        127
2  rio de janeiro         96
3  belo horizonte         68
4  ribeirao preto         52
5       guarulhos         50
6        ibitinga         49
7     santo andre         45
8        campinas         41
9         maringa         40

Seller terbanyak terdapat di kota sao paulo

## Products

In [109]:
df_products.head()

product_id product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5            perfumaria   
1  6a2fb4dd53d2cdb88e0432f1284a004c            perfumaria   
2  0d009643171aee696f4733340bc2fdd0            perfumaria   
3  b1eae565a61935e0011ee7682fef9dc9            perfumaria   
4  8da90b37f0fb171b4877c124f965b1f6            perfumaria   

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0   
1                 39.0                       346.0                 2.0   
2                 52.0                       150.0                 1.0   
3                 49.0                       460.0                 2.0   
4                 56.0                       733.0                 3.0   

   product_weight_g  product_length_cm  product_height_cm  product_width_cm  \
0             225.0               16.0               10.0              14.0   
1             400.0               27.0                5.0              20.0   
2             422.0               21.0               16.0              18.0   
3             267.0               17.0               13.0              17.0   
4             377.0               18.0               13.0              15.0   

  product_category_name_english  
0                     perfumery  
1                     perfumery  
2                     perfumery  
3                     perfumery  
4                     perfumery

In [110]:
df_products.rename(columns = {'product_category_name_english':'product_name'}, inplace = True)
df_products.drop('product_category_name', axis=1, inplace=True)
df_products.head()

product_id  product_name_lenght  \
0  1e9e8ef04dbcff4541ed26657ea517e5                 40.0   
1  6a2fb4dd53d2cdb88e0432f1284a004c                 39.0   
2  0d009643171aee696f4733340bc2fdd0                 52.0   
3  b1eae565a61935e0011ee7682fef9dc9                 49.0   
4  8da90b37f0fb171b4877c124f965b1f6                 56.0   

   product_description_lenght  product_photos_qty  product_weight_g  \
0                       287.0                 1.0             225.0   
1                       346.0                 2.0             400.0   
2                       150.0                 1.0             422.0   
3                       460.0                 2.0             267.0   
4                       733.0                 3.0             377.0   

   product_length_cm  product_height_cm  product_width_cm product_name  
0               16.0               10.0              14.0    perfumery  
1               27.0                5.0              20.0    perfumery  
2               21.0               16.0              18.0    perfumery  
3               17.0               13.0              17.0    perfumery  
4               18.0               13.0              15.0    perfumery

In [111]:
df_products.product_name.unique()

array(['perfumery', 'art', 'sports_leisure', 'baby', 'housewares',
       'musical_instruments', 'cool_stuff', 'furniture_decor',
       'home_appliances', 'toys', 'bed_bath_table',
       'construction_tools_safety', 'computers_accessories',
       'health_beauty', 'luggage_accessories', 'garden_tools',
       'office_furniture', 'auto', 'electronics', 'fashion_shoes',
       'telephony', 'stationery', 'fashion_bags_accessories', 'computers',
       'home_construction', 'watches_gifts',
       'construction_tools_construction', 'pet_shop', 'small_appliances',
       'agro_industry_and_commerce', 'furniture_living_room',
       'signaling_and_security', 'air_conditioning', 'consoles_games',
       'books_general_interest', 'costruction_tools_tools',
       'fashion_underwear_beach', 'fashion_male_clothing',
       'kitchen_dining_laundry_garden_furniture',
       'industry_commerce_and_business', 'fixed_telephony',
       'construction_tools_lights', 'books_technical',
       'home_app

In [112]:
df_products.groupby(by="product_name").agg({
    "product_id": "nunique",
    "product_weight_g": "mean",
    "product_photos_qty": "mean"
}).sort_values(by="product_id",ascending=False).reset_index().nlargest(10, "product_id")

product_name  product_id  product_weight_g  product_photos_qty
0         bed_bath_table        3029       2456.405084            1.392539
1         sports_leisure        2867       2024.670736            2.135333
2        furniture_decor        2657       3008.266842            2.400828
3          health_beauty        2444       1434.793781            1.624386
4             housewares        2335       3020.793576            2.212848
5                   auto        1900       2654.650526            2.636842
6  computers_accessories        1639        898.377669            1.987797
7                   toys        1411       1869.356485            2.458540
8          watches_gifts        1329        509.287434            2.234011
9              telephony        1134        236.506173            2.759259

Produk yang paling banyak dibeli adalah bed_bath_table

In [113]:
df_products.groupby(by="product_name").agg({
    "product_id": "nunique",
    "product_weight_g": "mean",
    "product_photos_qty": "mean"
}).sort_values(by="product_id",ascending=False).reset_index().nsmallest(10, "product_id")

product_name  product_id  product_weight_g  \
70                  cds_dvds_musicals           1        550.000000   
69              security_and_services           2        812.500000   
67                     home_comfort_2           5       1467.600000   
68          fashion_childrens_clothes           5        324.000000   
66             tablets_printing_image           9        381.444444   
64                         la_cuisine          10       4350.000000   
65  furniture_mattress_and_upholstery          10      13190.000000   
63                diapers_and_hygiene          12       1037.500000   
62                            flowers          14       1403.571429   
60              arts_and_craftmanship          19       1164.578947   

    product_photos_qty  
70            2.000000  
69            2.500000  
67            1.200000  
68            3.200000  
66            3.000000  
64            1.100000  
65            2.000000  
63            2.166667  
62            1.214286  
60            3.000000

Produk yang paling sedikit dibeli adalah bed_bath_table

## Geolocation

In [114]:
df_geo.head()

geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292   
1                         1046       -23.546081       -46.644820   
2                         1046       -23.546129       -46.642951   
3                         1041       -23.544392       -46.639499   
4                         1035       -23.541578       -46.641607   

  geolocation_city geolocation_state  
0        sao paulo                SP  
1        sao paulo                SP  
2        sao paulo                SP  
3        sao paulo                SP  
4        sao paulo                SP

In [115]:
df_geo.geolocation_city.unique()

array(['sao paulo', 'são paulo', 'sao bernardo do campo', ..., 'ciríaco',
       'estação', 'vila lângaro'], dtype=object)

In [116]:
df_geo.geolocation_city.nunique()

8011

In [117]:
df_geo.geolocation_state.unique()

array(['SP', 'RN', 'AC', 'RJ', 'ES', 'MG', 'BA', 'SE', 'PE', 'AL', 'PB',
       'CE', 'PI', 'MA', 'PA', 'AP', 'AM', 'RR', 'DF', 'GO', 'RO', 'TO',
       'MT', 'MS', 'RS', 'PR', 'SC'], dtype=object)

In [118]:
df_geo.geolocation_state.nunique()

27

## CUSTOMER AND ORDER

### customer

In [119]:
df_customer.shape

(99441, 5)

In [120]:
df_customer["customer_id"].nunique()

99441

In [121]:
df_customer.head()

customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0   
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3   
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e   
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c   
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066   

   customer_zip_code_prefix          customer_city customer_state  
0                     14409                 franca             SP  
1                      9790  sao bernardo do campo             SP  
2                      1151              sao paulo             SP  
3                      8775        mogi das cruzes             SP  
4                     13056               campinas             SP

### Orders

In [122]:
df_orders.shape

(117329, 28)

In [123]:
df_orders["customer_id"].nunique()

97916

In [124]:
df_orders.head()

order_id                       customer_id  \
0  36989eb07a0de2d3d3129eea35553875  aadd27185177fc7ac9b364898ac09343   
1  36989eb07a0de2d3d3129eea35553875  aadd27185177fc7ac9b364898ac09343   
2  7033745709b7cf1bac7d2533663592de  7f0ca17bb33b230b47459437cf0682c7   
3  5204d67853f827d1ee32810bf8f2d6c2  3dc7eb6da6c008460353d9a171e8fe6d   
4  5204d67853f827d1ee32810bf8f2d6c2  3dc7eb6da6c008460353d9a171e8fe6d   

  order_status order_purchase_timestamp order_approved_at  \
0    delivered                       13        2016-10-04   
1    delivered                       13        2016-10-04   
2    delivered                       14        2016-10-04   
3    delivered                       17        2016-10-06   
4    delivered                       17        2016-10-06   

  order_delivered_carrier_date order_delivered_customer_date  \
0                   2016-10-08                    2016-10-11   
1                   2016-10-08                    2016-10-11   
2                   2016-10-08                    2016-10-11   
3                   2016-10-10                    2016-10-13   
4                   2016-10-10                    2016-10-13   

  order_estimated_delivery_date delivery_status  order_item_id  \
0                    2016-12-06     Tepat Waktu              1   
1                    2016-12-06     Tepat Waktu              2   
2                    2016-11-30     Tepat Waktu              1   
3                    2016-11-28     Tepat Waktu              1   
4                    2016-11-28     Tepat Waktu              1   

                         product_id                         seller_id  \
0  43bb8825dd6838251606e5e4130cfff4  939f6e231201f26803cb5c3a3d2940b3   
1  43bb8825dd6838251606e5e4130cfff4  939f6e231201f26803cb5c3a3d2940b3   
2  35084deab9603bbb6035bb8638b1df89  df560393f3a51e74553ab94004ba5c87   
3  b6f134ff2933bb0ee1f36e2865f21a91  0c8380b62e38e8a1e6adbeba7eb9688c   
4  b6f134ff2933bb0ee1f36e2865f21a91  0c8380b62e38e8a1e6adbeba7eb9688c   

   shipping_limit_date  price  freight_value  payment_sequential payment_type  \
0  2016-10-08 13:46:32   23.9          26.82                   1  credit_card   
1  2016-10-08 13:46:32   23.9          26.82                   1  credit_card   
2  2016-10-08 14:46:49   93.9          17.61                   1  credit_card   
3  2016-10-10 15:45:44  139.9          21.34                   2      voucher   
4  2016-10-10 15:45:44  139.9          21.34                   1  credit_card   

   payment_installments  payment_value                         review_id  \
0                    10         101.44  7d58a5b4bc501c1ece8972fa04351be2   
1                    10         101.44  7d58a5b4bc501c1ece8972fa04351be2   
2                     4         111.51  a0ba97ce98f76cf57bb2c5530513be70   
3                     1          74.65  faf9ce3802b882a10bcd548f421ea9ff   
4                     3          86.59  faf9ce3802b882a10bcd548f421ea9ff   

   review_score review_creation_date review_answer_timestamp  order_year  \
0             5           2016-10-20                      01        2016   
1             5           2016-10-20                      01        2016   
2             3           2016-10-25                      23        2016   
3             5           2016-10-18                      19        2016   
4             5           2016-10-18                      19        2016   

   order_month order_month_name order_purchase_time review_answer_time  
0           10          october           afternoon              night  
1           10          october           afternoon              night  
2           10          october           afternoon              night  
3           10          october           afternoon            evening  
4           10          october           afternoon            evening

### Pelanggan aktif dan non aktif

In [125]:
df_order_only =  df_orders.customer_id
df_customer["status_customer"] = np.where(df_customer["customer_id"].isin(df_orders['customer_id']), 'aktif', 'nonaktif')
df_customer.groupby(by="status_customer").customer_id.count()

status_customer
aktif       97916
nonaktif     1525
Name: customer_id, dtype: int64

Sebagian besar pelanggan adalah pelanggan aktif yaitu sebanyak 97916 pelanggan

# PRODUCT AND ORDER

### PRODUCT

In [126]:
df_products.head()

product_id  product_name_lenght  \
0  1e9e8ef04dbcff4541ed26657ea517e5                 40.0   
1  6a2fb4dd53d2cdb88e0432f1284a004c                 39.0   
2  0d009643171aee696f4733340bc2fdd0                 52.0   
3  b1eae565a61935e0011ee7682fef9dc9                 49.0   
4  8da90b37f0fb171b4877c124f965b1f6                 56.0   

   product_description_lenght  product_photos_qty  product_weight_g  \
0                       287.0                 1.0             225.0   
1                       346.0                 2.0             400.0   
2                       150.0                 1.0             422.0   
3                       460.0                 2.0             267.0   
4                       733.0                 3.0             377.0   

   product_length_cm  product_height_cm  product_width_cm product_name  
0               16.0               10.0              14.0    perfumery  
1               27.0                5.0              20.0    perfumery  
2               21.0               16.0              18.0    perfumery  
3               17.0               13.0              17.0    perfumery  
4               18.0               13.0              15.0    perfumery

In [127]:
df_products.describe(include="all")

product_id  product_name_lenght  \
count                              32327         32327.000000   
unique                             32327                  NaN   
top     1e9e8ef04dbcff4541ed26657ea517e5                  NaN   
freq                                   1                  NaN   
mean                                 NaN            48.473722   
std                                  NaN            10.246346   
min                                  NaN             5.000000   
25%                                  NaN            42.000000   
50%                                  NaN            51.000000   
75%                                  NaN            57.000000   
max                                  NaN            76.000000   

        product_description_lenght  product_photos_qty  product_weight_g  \
count                 32327.000000        32327.000000      32327.000000   
unique                         NaN                 NaN               NaN   
top                            NaN                 NaN               NaN   
freq                           NaN                 NaN               NaN   
mean                    771.517277            2.188790       2276.960807   
std                     635.189674            1.736767       4279.734063   
min                       4.000000            1.000000          0.000000   
25%                     339.000000            1.000000        300.000000   
50%                     595.000000            1.000000        700.000000   
75%                     972.000000            3.000000       1900.000000   
max                    3992.000000           20.000000      40425.000000   

        product_length_cm  product_height_cm  product_width_cm    product_name  
count        32327.000000       32327.000000      32327.000000           32327  
unique                NaN                NaN               NaN              71  
top                   NaN                NaN               NaN  bed_bath_table  
freq                  NaN                NaN               NaN            3029  
mean            30.856498          16.955950         23.208464             NaN  
std             16.958460          13.637246         12.080665             NaN  
min              7.000000           2.000000          6.000000             NaN  
25%             18.000000           8.000000         15.000000             NaN  
50%             25.000000          13.000000         20.000000             NaN  
75%             38.000000          20.500000         30.000000             NaN  
max            105.000000         105.000000        118.000000             NaN

In [128]:
df_products.isna().sum()

product_id                    0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
product_name                  0
dtype: int64

### ORDER

In [129]:
df_orders.head()

order_id                       customer_id  \
0  36989eb07a0de2d3d3129eea35553875  aadd27185177fc7ac9b364898ac09343   
1  36989eb07a0de2d3d3129eea35553875  aadd27185177fc7ac9b364898ac09343   
2  7033745709b7cf1bac7d2533663592de  7f0ca17bb33b230b47459437cf0682c7   
3  5204d67853f827d1ee32810bf8f2d6c2  3dc7eb6da6c008460353d9a171e8fe6d   
4  5204d67853f827d1ee32810bf8f2d6c2  3dc7eb6da6c008460353d9a171e8fe6d   

  order_status order_purchase_timestamp order_approved_at  \
0    delivered                       13        2016-10-04   
1    delivered                       13        2016-10-04   
2    delivered                       14        2016-10-04   
3    delivered                       17        2016-10-06   
4    delivered                       17        2016-10-06   

  order_delivered_carrier_date order_delivered_customer_date  \
0                   2016-10-08                    2016-10-11   
1                   2016-10-08                    2016-10-11   
2                   2016-10-08                    2016-10-11   
3                   2016-10-10                    2016-10-13   
4                   2016-10-10                    2016-10-13   

  order_estimated_delivery_date delivery_status  order_item_id  \
0                    2016-12-06     Tepat Waktu              1   
1                    2016-12-06     Tepat Waktu              2   
2                    2016-11-30     Tepat Waktu              1   
3                    2016-11-28     Tepat Waktu              1   
4                    2016-11-28     Tepat Waktu              1   

                         product_id                         seller_id  \
0  43bb8825dd6838251606e5e4130cfff4  939f6e231201f26803cb5c3a3d2940b3   
1  43bb8825dd6838251606e5e4130cfff4  939f6e231201f26803cb5c3a3d2940b3   
2  35084deab9603bbb6035bb8638b1df89  df560393f3a51e74553ab94004ba5c87   
3  b6f134ff2933bb0ee1f36e2865f21a91  0c8380b62e38e8a1e6adbeba7eb9688c   
4  b6f134ff2933bb0ee1f36e2865f21a91  0c8380b62e38e8a1e6adbeba7eb9688c   

   shipping_limit_date  price  freight_value  payment_sequential payment_type  \
0  2016-10-08 13:46:32   23.9          26.82                   1  credit_card   
1  2016-10-08 13:46:32   23.9          26.82                   1  credit_card   
2  2016-10-08 14:46:49   93.9          17.61                   1  credit_card   
3  2016-10-10 15:45:44  139.9          21.34                   2      voucher   
4  2016-10-10 15:45:44  139.9          21.34                   1  credit_card   

   payment_installments  payment_value                         review_id  \
0                    10         101.44  7d58a5b4bc501c1ece8972fa04351be2   
1                    10         101.44  7d58a5b4bc501c1ece8972fa04351be2   
2                     4         111.51  a0ba97ce98f76cf57bb2c5530513be70   
3                     1          74.65  faf9ce3802b882a10bcd548f421ea9ff   
4                     3          86.59  faf9ce3802b882a10bcd548f421ea9ff   

   review_score review_creation_date review_answer_timestamp  order_year  \
0             5           2016-10-20                      01        2016   
1             5           2016-10-20                      01        2016   
2             3           2016-10-25                      23        2016   
3             5           2016-10-18                      19        2016   
4             5           2016-10-18                      19        2016   

   order_month order_month_name order_purchase_time review_answer_time  
0           10          october           afternoon              night  
1           10          october           afternoon              night  
2           10          october           afternoon              night  
3           10          october           afternoon            evening  
4           10          october           afternoon            evening

In [130]:
df_orders.describe(include="all")

order_id                       customer_id  \
count                             117329                            117329   
unique                             97916                             97916   
top     895ab968e7bb0d5659d16cd74cd1650c  270c23a11d024a44c896d1894b261a83   
freq                                  63                                63   
mean                                 NaN                               NaN   
min                                  NaN                               NaN   
25%                                  NaN                               NaN   
50%                                  NaN                               NaN   
75%                                  NaN                               NaN   
max                                  NaN                               NaN   
std                                  NaN                               NaN   

       order_status order_purchase_timestamp              order_approved_at  \
count        117329                   117329                         117329   
unique            7                       24                            NaN   
top       delivered                       16                            NaN   
freq         114859                     7954                            NaN   
mean            NaN                      NaN  2017-12-30 09:27:30.712100352   
min             NaN                      NaN            2016-10-04 00:00:00   
25%             NaN                      NaN            2017-09-12 00:00:00   
50%             NaN                      NaN            2018-01-18 00:00:00   
75%             NaN                      NaN            2018-05-04 00:00:00   
max             NaN                      NaN            2018-09-03 00:00:00   
std             NaN                      NaN                            NaN   

         order_delivered_carrier_date  order_delivered_customer_date  \
count                          117329                         117329   
unique                            NaN                            NaN   
top                               NaN                            NaN   
freq                              NaN                            NaN   
mean    2018-01-05 12:00:36.451346176  2018-01-18 03:19:10.886822912   
min               2016-10-08 00:00:00            2016-10-11 00:00:00   
25%               2017-09-15 00:00:00            2017-09-27 00:00:00   
50%               2018-01-24 00:00:00            2018-02-06 00:00:00   
75%               2018-05-09 00:00:00            2018-05-19 00:00:00   
max               2018-09-11 00:00:00            2018-10-17 00:00:00   
std                               NaN                            NaN   

        order_estimated_delivery_date delivery_status  order_item_id  \
count                          117329          117329  117329.000000   
unique                            NaN               2            NaN   
top                               NaN     Tepat Waktu            NaN   
freq                              NaN          108469            NaN   
mean    2018-01-23 07:08:36.977047296             NaN       1.194121   
min               2016-10-20 00:00:00             NaN       1.000000   
25%               2017-10-03 00:00:00             NaN       1.000000   
50%               2018-02-14 00:00:00             NaN       1.000000   
75%               2018-05-25 00:00:00             NaN       1.000000   
max               2018-10-25 00:00:00             NaN      21.000000   
std                               NaN             NaN       0.684225   

                              product_id                         seller_id  \
count                             117329                            117329   
unique                             32789                              3090   
top     aca2eb7d00ea1a7b8ebd4e68314663af  4a3ca9315b744ce9f8e9374361493884   
freq                                 533                              2128   
mean                      

In [131]:
df_orders.isna().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
delivery_status                  0
order_item_id                    0
product_id                       0
seller_id                        0
shipping_limit_date              0
price                            0
freight_value                    0
payment_sequential               0
payment_type                     0
payment_installments             0
payment_value                    0
review_id                        0
review_score                     0
review_creation_date             0
review_answer_timestamp          0
order_year                       0
order_month                      0
order_month_name                 0
order_purchase_time              0
review_answer_time               0
dtype: int64

## Produk yang tidak pernah dibeli pelanggan

In [132]:
df_product_only =  df_orders.product_id
df_products["status_products"] = np.where(df_products["product_id"].isin(df_orders['product_id']), 'Ordered', 'No order')
df_products.groupby(by="status_products").product_id.count()

status_products
No order      157
Ordered     32170
Name: product_id, dtype: int64

Sebagian besar produk yang ada berhasil terjual ke pelanggan sedangkan ada 157 produk yang belum pernah dibeli pelanggan

## Merge Data Produk dan Order

In [133]:
orders_products_df = pd.merge(
    left=df_orders,
    right=df_products,
    how="inner",
    left_on="product_id",
    right_on="product_id"
)
orders_products_df.head()

order_id                       customer_id  \
0  36989eb07a0de2d3d3129eea35553875  aadd27185177fc7ac9b364898ac09343   
1  36989eb07a0de2d3d3129eea35553875  aadd27185177fc7ac9b364898ac09343   
2  7033745709b7cf1bac7d2533663592de  7f0ca17bb33b230b47459437cf0682c7   
3  5204d67853f827d1ee32810bf8f2d6c2  3dc7eb6da6c008460353d9a171e8fe6d   
4  5204d67853f827d1ee32810bf8f2d6c2  3dc7eb6da6c008460353d9a171e8fe6d   

  order_status order_purchase_timestamp order_approved_at  \
0    delivered                       13        2016-10-04   
1    delivered                       13        2016-10-04   
2    delivered                       14        2016-10-04   
3    delivered                       17        2016-10-06   
4    delivered                       17        2016-10-06   

  order_delivered_carrier_date order_delivered_customer_date  \
0                   2016-10-08                    2016-10-11   
1                   2016-10-08                    2016-10-11   
2                   2016-10-08                    2016-10-11   
3                   2016-10-10                    2016-10-13   
4                   2016-10-10                    2016-10-13   

  order_estimated_delivery_date delivery_status  order_item_id  \
0                    2016-12-06     Tepat Waktu              1   
1                    2016-12-06     Tepat Waktu              2   
2                    2016-11-30     Tepat Waktu              1   
3                    2016-11-28     Tepat Waktu              1   
4                    2016-11-28     Tepat Waktu              1   

                         product_id                         seller_id  \
0  43bb8825dd6838251606e5e4130cfff4  939f6e231201f26803cb5c3a3d2940b3   
1  43bb8825dd6838251606e5e4130cfff4  939f6e231201f26803cb5c3a3d2940b3   
2  35084deab9603bbb6035bb8638b1df89  df560393f3a51e74553ab94004ba5c87   
3  b6f134ff2933bb0ee1f36e2865f21a91  0c8380b62e38e8a1e6adbeba7eb9688c   
4  b6f134ff2933bb0ee1f36e2865f21a91  0c8380b62e38e8a1e6adbeba7eb9688c   

   shipping_limit_date  price  freight_value  payment_sequential payment_type  \
0  2016-10-08 13:46:32   23.9          26.82                   1  credit_card   
1  2016-10-08 13:46:32   23.9          26.82                   1  credit_card   
2  2016-10-08 14:46:49   93.9          17.61                   1  credit_card   
3  2016-10-10 15:45:44  139.9          21.34                   2      voucher   
4  2016-10-10 15:45:44  139.9          21.34                   1  credit_card   

   payment_installments  payment_value                         review_id  \
0                    10         101.44  7d58a5b4bc501c1ece8972fa04351be2   
1                    10         101.44  7d58a5b4bc501c1ece8972fa04351be2   
2                     4         111.51  a0ba97ce98f76cf57bb2c5530513be70   
3                     1          74.65  faf9ce3802b882a10bcd548f421ea9ff   
4                     3          86.59  faf9ce3802b882a10bcd548f421ea9ff   

   review_score review_creation_date review_answer_timestamp  order_year  \
0             5           2016-10-20                      01        2016   
1             5           2016-10-20                      01        2016   
2             3           2016-10-25                      23        2016   
3             5           2016-10-18                      19        2016   
4             5           2016-10-18                      19        2016   

   order_month order_month_name order_purchase_time review_answer_time  \
0           10          october           afternoon              night   
1           10          october           afternoon              night   
2           10          october           afternoon              night   
3           10          october           afternoon            evening   
4           10          october           afternoon            evening   

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 33.0                       259.0                 2.0   
1     

In [134]:
orders_products_df.isna().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
delivery_status                  0
order_item_id                    0
product_id                       0
seller_id                        0
shipping_limit_date              0
price                            0
freight_value                    0
payment_sequential               0
payment_type                     0
payment_installments             0
payment_value                    0
review_id                        0
review_score                     0
review_creation_date             0
review_answer_timestamp          0
order_year                       0
order_month                      0
order_month_name                 0
order_purchase_time              0
review_answer_time               0
product_name_lenght 

In [135]:
orders_products_df.groupby(by="product_name").agg({
    "order_id": "nunique",
    "order_item_id": "sum",
    "payment_value": "sum",
    "review_score": "mean"
}).nlargest(10, "payment_value")

order_id  order_item_id  payment_value  review_score
product_name                                                               
bed_bath_table             9313          14608     1725465.67      3.890605
health_beauty              8770          11368     1646292.53      4.137973
computers_accessories      6649          10222     1592611.66      3.936089
furniture_decor            6398          12038     1427214.01      3.912158
watches_gifts              5576           6765     1420682.17      4.017692
sports_leisure             7669          10273     1390581.87      4.107470
housewares                 5843           9503     1091709.15      4.060428
garden_tools               3496           6104      834757.45      4.023914
auto                       3877           4826      802254.74      4.064279
cool_stuff                 3599           4261      772616.70      4.140767

walaupun bed_bath_table menjadi produk paling laku, produk ini mendapatkan rating yang tidak terlalu tinggi yaitu rata-rata 3.8 lebih rendah daripada produk lainnya yang berada di 10 produk paling laku

# ORDER AND PRODUCT AND SELLER

### Order dan Produk

In [136]:
orders_products_df.head()

order_id                       customer_id  \
0  36989eb07a0de2d3d3129eea35553875  aadd27185177fc7ac9b364898ac09343   
1  36989eb07a0de2d3d3129eea35553875  aadd27185177fc7ac9b364898ac09343   
2  7033745709b7cf1bac7d2533663592de  7f0ca17bb33b230b47459437cf0682c7   
3  5204d67853f827d1ee32810bf8f2d6c2  3dc7eb6da6c008460353d9a171e8fe6d   
4  5204d67853f827d1ee32810bf8f2d6c2  3dc7eb6da6c008460353d9a171e8fe6d   

  order_status order_purchase_timestamp order_approved_at  \
0    delivered                       13        2016-10-04   
1    delivered                       13        2016-10-04   
2    delivered                       14        2016-10-04   
3    delivered                       17        2016-10-06   
4    delivered                       17        2016-10-06   

  order_delivered_carrier_date order_delivered_customer_date  \
0                   2016-10-08                    2016-10-11   
1                   2016-10-08                    2016-10-11   
2                   2016-10-08                    2016-10-11   
3                   2016-10-10                    2016-10-13   
4                   2016-10-10                    2016-10-13   

  order_estimated_delivery_date delivery_status  order_item_id  \
0                    2016-12-06     Tepat Waktu              1   
1                    2016-12-06     Tepat Waktu              2   
2                    2016-11-30     Tepat Waktu              1   
3                    2016-11-28     Tepat Waktu              1   
4                    2016-11-28     Tepat Waktu              1   

                         product_id                         seller_id  \
0  43bb8825dd6838251606e5e4130cfff4  939f6e231201f26803cb5c3a3d2940b3   
1  43bb8825dd6838251606e5e4130cfff4  939f6e231201f26803cb5c3a3d2940b3   
2  35084deab9603bbb6035bb8638b1df89  df560393f3a51e74553ab94004ba5c87   
3  b6f134ff2933bb0ee1f36e2865f21a91  0c8380b62e38e8a1e6adbeba7eb9688c   
4  b6f134ff2933bb0ee1f36e2865f21a91  0c8380b62e38e8a1e6adbeba7eb9688c   

   shipping_limit_date  price  freight_value  payment_sequential payment_type  \
0  2016-10-08 13:46:32   23.9          26.82                   1  credit_card   
1  2016-10-08 13:46:32   23.9          26.82                   1  credit_card   
2  2016-10-08 14:46:49   93.9          17.61                   1  credit_card   
3  2016-10-10 15:45:44  139.9          21.34                   2      voucher   
4  2016-10-10 15:45:44  139.9          21.34                   1  credit_card   

   payment_installments  payment_value                         review_id  \
0                    10         101.44  7d58a5b4bc501c1ece8972fa04351be2   
1                    10         101.44  7d58a5b4bc501c1ece8972fa04351be2   
2                     4         111.51  a0ba97ce98f76cf57bb2c5530513be70   
3                     1          74.65  faf9ce3802b882a10bcd548f421ea9ff   
4                     3          86.59  faf9ce3802b882a10bcd548f421ea9ff   

   review_score review_creation_date review_answer_timestamp  order_year  \
0             5           2016-10-20                      01        2016   
1             5           2016-10-20                      01        2016   
2             3           2016-10-25                      23        2016   
3             5           2016-10-18                      19        2016   
4             5           2016-10-18                      19        2016   

   order_month order_month_name order_purchase_time review_answer_time  \
0           10          october           afternoon              night   
1           10          october           afternoon              night   
2           10          october           afternoon              night   
3           10          october           afternoon            evening   
4           10          october           afternoon            evening   

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 33.0                       259.0                 2.0   
1     

### Seller

In [137]:
df_sellers.head()

seller_id  seller_zip_code_prefix  \
0  3442f8959a84dea7ee197c632cb2df15                   13023   
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844   
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031   
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195   
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914   

         seller_city seller_state  
0           campinas           SP  
1         mogi guacu           SP  
2     rio de janeiro           RJ  
3          sao paulo           SP  
4  braganca paulista           SP

## Merge Data Order-Produk dan Sellers

In [138]:
sellers_orders_products_df = pd.merge(
    left=orders_products_df,
    right=df_sellers,
    how="left",
    left_on="seller_id",
    right_on="seller_id"
)
sellers_orders_products_df.head()

order_id                       customer_id  \
0  36989eb07a0de2d3d3129eea35553875  aadd27185177fc7ac9b364898ac09343   
1  36989eb07a0de2d3d3129eea35553875  aadd27185177fc7ac9b364898ac09343   
2  7033745709b7cf1bac7d2533663592de  7f0ca17bb33b230b47459437cf0682c7   
3  5204d67853f827d1ee32810bf8f2d6c2  3dc7eb6da6c008460353d9a171e8fe6d   
4  5204d67853f827d1ee32810bf8f2d6c2  3dc7eb6da6c008460353d9a171e8fe6d   

  order_status order_purchase_timestamp order_approved_at  \
0    delivered                       13        2016-10-04   
1    delivered                       13        2016-10-04   
2    delivered                       14        2016-10-04   
3    delivered                       17        2016-10-06   
4    delivered                       17        2016-10-06   

  order_delivered_carrier_date order_delivered_customer_date  \
0                   2016-10-08                    2016-10-11   
1                   2016-10-08                    2016-10-11   
2                   2016-10-08                    2016-10-11   
3                   2016-10-10                    2016-10-13   
4                   2016-10-10                    2016-10-13   

  order_estimated_delivery_date delivery_status  order_item_id  \
0                    2016-12-06     Tepat Waktu              1   
1                    2016-12-06     Tepat Waktu              2   
2                    2016-11-30     Tepat Waktu              1   
3                    2016-11-28     Tepat Waktu              1   
4                    2016-11-28     Tepat Waktu              1   

                         product_id                         seller_id  \
0  43bb8825dd6838251606e5e4130cfff4  939f6e231201f26803cb5c3a3d2940b3   
1  43bb8825dd6838251606e5e4130cfff4  939f6e231201f26803cb5c3a3d2940b3   
2  35084deab9603bbb6035bb8638b1df89  df560393f3a51e74553ab94004ba5c87   
3  b6f134ff2933bb0ee1f36e2865f21a91  0c8380b62e38e8a1e6adbeba7eb9688c   
4  b6f134ff2933bb0ee1f36e2865f21a91  0c8380b62e38e8a1e6adbeba7eb9688c   

   shipping_limit_date  price  freight_value  payment_sequential payment_type  \
0  2016-10-08 13:46:32   23.9          26.82                   1  credit_card   
1  2016-10-08 13:46:32   23.9          26.82                   1  credit_card   
2  2016-10-08 14:46:49   93.9          17.61                   1  credit_card   
3  2016-10-10 15:45:44  139.9          21.34                   2      voucher   
4  2016-10-10 15:45:44  139.9          21.34                   1  credit_card   

   payment_installments  payment_value                         review_id  \
0                    10         101.44  7d58a5b4bc501c1ece8972fa04351be2   
1                    10         101.44  7d58a5b4bc501c1ece8972fa04351be2   
2                     4         111.51  a0ba97ce98f76cf57bb2c5530513be70   
3                     1          74.65  faf9ce3802b882a10bcd548f421ea9ff   
4                     3          86.59  faf9ce3802b882a10bcd548f421ea9ff   

   review_score review_creation_date review_answer_timestamp  order_year  \
0             5           2016-10-20                      01        2016   
1             5           2016-10-20                      01        2016   
2             3           2016-10-25                      23        2016   
3             5           2016-10-18                      19        2016   
4             5           2016-10-18                      19        2016   

   order_month order_month_name order_purchase_time review_answer_time  \
0           10          october           afternoon              night   
1           10          october           afternoon              night   
2           10          october           afternoon              night   
3           10          october           afternoon            evening   
4           10          october           afternoon            evening   

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 33.0                       259.0                 2.0   
1     

In [139]:
sellers_orders_products_df.groupby(by="seller_city").agg({
    "order_id": "nunique",
    "payment_value": "sum",
    "product_name": pd.Series.mode
}).nlargest(10, "payment_value")

order_id  payment_value           product_name
seller_city                                                          
sao paulo                 24215     4154006.77        furniture_decor
ibitinga                   6473     1060183.69         bed_bath_table
curitiba                   2678      646929.93        furniture_decor
itaquaquecetuba            1232      574161.05       office_furniture
rio de janeiro             2117      478609.31                   toys
guarulhos                  1694      447877.58                   auto
sao jose do rio preto      1957      413318.07           garden_tools
ribeirao preto             1985      386479.18         sports_leisure
maringa                    1848      386153.96  computers_accessories
piracicaba                 1608      358703.21         bed_bath_table

Kota yang paling banyak transaksinya adalah sao paulo dengan produk yang terjual paling banyak adalah furniture_decor

# JOIN ALL DATA

In [140]:
df_customer.head()

customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0   
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3   
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e   
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c   
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066   

   customer_zip_code_prefix          customer_city customer_state  \
0                     14409                 franca             SP   
1                      9790  sao bernardo do campo             SP   
2                      1151              sao paulo             SP   
3                      8775        mogi das cruzes             SP   
4                     13056               campinas             SP   

  status_customer  
0           aktif  
1           aktif  
2           aktif  
3           aktif  
4           aktif

In [141]:
sellers_orders_products_df.head()

order_id                       customer_id  \
0  36989eb07a0de2d3d3129eea35553875  aadd27185177fc7ac9b364898ac09343   
1  36989eb07a0de2d3d3129eea35553875  aadd27185177fc7ac9b364898ac09343   
2  7033745709b7cf1bac7d2533663592de  7f0ca17bb33b230b47459437cf0682c7   
3  5204d67853f827d1ee32810bf8f2d6c2  3dc7eb6da6c008460353d9a171e8fe6d   
4  5204d67853f827d1ee32810bf8f2d6c2  3dc7eb6da6c008460353d9a171e8fe6d   

  order_status order_purchase_timestamp order_approved_at  \
0    delivered                       13        2016-10-04   
1    delivered                       13        2016-10-04   
2    delivered                       14        2016-10-04   
3    delivered                       17        2016-10-06   
4    delivered                       17        2016-10-06   

  order_delivered_carrier_date order_delivered_customer_date  \
0                   2016-10-08                    2016-10-11   
1                   2016-10-08                    2016-10-11   
2                   2016-10-08                    2016-10-11   
3                   2016-10-10                    2016-10-13   
4                   2016-10-10                    2016-10-13   

  order_estimated_delivery_date delivery_status  order_item_id  \
0                    2016-12-06     Tepat Waktu              1   
1                    2016-12-06     Tepat Waktu              2   
2                    2016-11-30     Tepat Waktu              1   
3                    2016-11-28     Tepat Waktu              1   
4                    2016-11-28     Tepat Waktu              1   

                         product_id                         seller_id  \
0  43bb8825dd6838251606e5e4130cfff4  939f6e231201f26803cb5c3a3d2940b3   
1  43bb8825dd6838251606e5e4130cfff4  939f6e231201f26803cb5c3a3d2940b3   
2  35084deab9603bbb6035bb8638b1df89  df560393f3a51e74553ab94004ba5c87   
3  b6f134ff2933bb0ee1f36e2865f21a91  0c8380b62e38e8a1e6adbeba7eb9688c   
4  b6f134ff2933bb0ee1f36e2865f21a91  0c8380b62e38e8a1e6adbeba7eb9688c   

   shipping_limit_date  price  freight_value  payment_sequential payment_type  \
0  2016-10-08 13:46:32   23.9          26.82                   1  credit_card   
1  2016-10-08 13:46:32   23.9          26.82                   1  credit_card   
2  2016-10-08 14:46:49   93.9          17.61                   1  credit_card   
3  2016-10-10 15:45:44  139.9          21.34                   2      voucher   
4  2016-10-10 15:45:44  139.9          21.34                   1  credit_card   

   payment_installments  payment_value                         review_id  \
0                    10         101.44  7d58a5b4bc501c1ece8972fa04351be2   
1                    10         101.44  7d58a5b4bc501c1ece8972fa04351be2   
2                     4         111.51  a0ba97ce98f76cf57bb2c5530513be70   
3                     1          74.65  faf9ce3802b882a10bcd548f421ea9ff   
4                     3          86.59  faf9ce3802b882a10bcd548f421ea9ff   

   review_score review_creation_date review_answer_timestamp  order_year  \
0             5           2016-10-20                      01        2016   
1             5           2016-10-20                      01        2016   
2             3           2016-10-25                      23        2016   
3             5           2016-10-18                      19        2016   
4             5           2016-10-18                      19        2016   

   order_month order_month_name order_purchase_time review_answer_time  \
0           10          october           afternoon              night   
1           10          october           afternoon              night   
2           10          october           afternoon              night   
3           10          october           afternoon            evening   
4           10          october           afternoon            evening   

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 33.0                       259.0                 2.0   
1     

In [142]:
all_df = pd.merge(
    left=sellers_orders_products_df,
    right=df_customer,
    how="left",
    left_on="customer_id",
    right_on="customer_id"
)
all_df.head()

order_id                       customer_id  \
0  36989eb07a0de2d3d3129eea35553875  aadd27185177fc7ac9b364898ac09343   
1  36989eb07a0de2d3d3129eea35553875  aadd27185177fc7ac9b364898ac09343   
2  7033745709b7cf1bac7d2533663592de  7f0ca17bb33b230b47459437cf0682c7   
3  5204d67853f827d1ee32810bf8f2d6c2  3dc7eb6da6c008460353d9a171e8fe6d   
4  5204d67853f827d1ee32810bf8f2d6c2  3dc7eb6da6c008460353d9a171e8fe6d   

  order_status order_purchase_timestamp order_approved_at  \
0    delivered                       13        2016-10-04   
1    delivered                       13        2016-10-04   
2    delivered                       14        2016-10-04   
3    delivered                       17        2016-10-06   
4    delivered                       17        2016-10-06   

  order_delivered_carrier_date order_delivered_customer_date  \
0                   2016-10-08                    2016-10-11   
1                   2016-10-08                    2016-10-11   
2                   2016-10-08                    2016-10-11   
3                   2016-10-10                    2016-10-13   
4                   2016-10-10                    2016-10-13   

  order_estimated_delivery_date delivery_status  order_item_id  \
0                    2016-12-06     Tepat Waktu              1   
1                    2016-12-06     Tepat Waktu              2   
2                    2016-11-30     Tepat Waktu              1   
3                    2016-11-28     Tepat Waktu              1   
4                    2016-11-28     Tepat Waktu              1   

                         product_id                         seller_id  \
0  43bb8825dd6838251606e5e4130cfff4  939f6e231201f26803cb5c3a3d2940b3   
1  43bb8825dd6838251606e5e4130cfff4  939f6e231201f26803cb5c3a3d2940b3   
2  35084deab9603bbb6035bb8638b1df89  df560393f3a51e74553ab94004ba5c87   
3  b6f134ff2933bb0ee1f36e2865f21a91  0c8380b62e38e8a1e6adbeba7eb9688c   
4  b6f134ff2933bb0ee1f36e2865f21a91  0c8380b62e38e8a1e6adbeba7eb9688c   

   shipping_limit_date  price  freight_value  payment_sequential payment_type  \
0  2016-10-08 13:46:32   23.9          26.82                   1  credit_card   
1  2016-10-08 13:46:32   23.9          26.82                   1  credit_card   
2  2016-10-08 14:46:49   93.9          17.61                   1  credit_card   
3  2016-10-10 15:45:44  139.9          21.34                   2      voucher   
4  2016-10-10 15:45:44  139.9          21.34                   1  credit_card   

   payment_installments  payment_value                         review_id  \
0                    10         101.44  7d58a5b4bc501c1ece8972fa04351be2   
1                    10         101.44  7d58a5b4bc501c1ece8972fa04351be2   
2                     4         111.51  a0ba97ce98f76cf57bb2c5530513be70   
3                     1          74.65  faf9ce3802b882a10bcd548f421ea9ff   
4                     3          86.59  faf9ce3802b882a10bcd548f421ea9ff   

   review_score review_creation_date review_answer_timestamp  order_year  \
0             5           2016-10-20                      01        2016   
1             5           2016-10-20                      01        2016   
2             3           2016-10-25                      23        2016   
3             5           2016-10-18                      19        2016   
4             5           2016-10-18                      19        2016   

   order_month order_month_name order_purchase_time review_answer_time  \
0           10          october           afternoon              night   
1           10          october           afternoon              night   
2           10          october           afternoon              night   
3           10          october           afternoon            evening   
4           10          october           afternoon            evening   

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 33.0                       259.0                 2.0   
1     

In [143]:
all_df.isna().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
delivery_status                  0
order_item_id                    0
product_id                       0
seller_id                        0
shipping_limit_date              0
price                            0
freight_value                    0
payment_sequential               0
payment_type                     0
payment_installments             0
payment_value                    0
review_id                        0
review_score                     0
review_creation_date             0
review_answer_timestamp          0
order_year                       0
order_month                      0
order_month_name                 0
order_purchase_time              0
review_answer_time               0
product_name_lenght 

In [144]:
all_df.groupby(by=["customer_city", "product_name"]).agg({
    "payment_value": "sum",
    "review_score": "mean"
}).nlargest(30, "payment_value")

payment_value  review_score
customer_city  product_name                                      
sao paulo      bed_bath_table             295685.33      3.994475
               computers_accessories      288500.24      4.017516
               health_beauty              263482.10      4.156250
               watches_gifts              194797.90      4.130081
               sports_leisure             192716.46      4.212722
               furniture_decor            192627.46      3.985999
               housewares                 165754.91      4.153901
rio de janeiro bed_bath_table             127026.50      3.652701
               fixed_telephony            112491.22      2.458333
               sports_leisure             107840.56      3.788779
               health_beauty              107022.94      4.071307
               watches_gifts              106593.31      3.804671
               computers_accessories      102793.75      3.921847
               furniture_decor            102006.88      3.715596
sao paulo      office_furniture            96734.20      3.493976
               toys                        87451.91      4.150888
rio de janeiro office_furniture            84180.70      3.395918
sao paulo      perfumery                   79364.13      4.211091
rio de janeiro housewares                  78049.31      3.899010
sao paulo      cool_stuff                  76481.90      4.258696
               auto                        74914.69      4.216312
               garden_tools                71764.63      4.158111
               baby                        65068.91      4.050682
rio de janeiro garden_tools                56140.98      3.604167
               toys                        54689.86      4.175793
sao paulo      telephony                   53908.41      4.069552
belo horizonte bed_bath_table              51078.09      3.810959
rio de janeiro cool_stuff                  50874.14      3.917293
belo horizonte health_beauty               44887.74      4.251799
brasilia       computers_accessories       43975.52      3.529412

walaupun di sao paulo produk yang paling banyak dibeli adalah furniture_decor, produk bed_bath_table tetap menjadi produk yang memiliki payment value paling besar

In [145]:
all_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115608 entries, 0 to 115607
Data columns (total 45 columns):
 #   Column                         Non-Null Count   Dtype         
---  ------                         --------------   -----         
 0   order_id                       115608 non-null  object        
 1   customer_id                    115608 non-null  object        
 2   order_status                   115608 non-null  object        
 3   order_purchase_timestamp       115608 non-null  object        
 4   order_approved_at              115608 non-null  datetime64[ns]
 5   order_delivered_carrier_date   115608 non-null  datetime64[ns]
 6   order_delivered_customer_date  115608 non-null  datetime64[ns]
 7   order_estimated_delivery_date  115608 non-null  datetime64[ns]
 8   delivery_status                115608 non-null  object        
 9   order_item_id                  115608 non-null  int64         
 10  product_id                     115608 non-null  object        
 11  

## Bagaimana tingkat penjualan perusahaan dalam beberapa bulan terakhir?

In [146]:
df_tingkat_penjualan_2016 = all_df[all_df.order_year == 2016]

tingkat_penjualan_2016 = df_tingkat_penjualan_2016.groupby(by='order_month').agg({
    "order_id": "nunique",
    "order_month_name" : pd.Series.mode,
    "payment_value" : "sum"
}).sort_values(by="order_month").reset_index()

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=tingkat_penjualan_2016["order_month_name"],
    y=tingkat_penjualan_2016["order_id"],
    mode='lines+markers',
    marker=dict(
        color='red',
        size=8,
    ),
    line=dict(
        width=3,
    ),
))

for x, y in zip(tingkat_penjualan_2016["order_month_name"], tingkat_penjualan_2016["order_id"]):
    fig.add_annotation(
        x=x,
        y=y+15,
        text=str(y),
        font=dict(
            size=12,
        ),
        showarrow=False,
        textangle=0,
    )

fig.update_layout(
    title="Tingkat Penjualan Tahun 2016",
    xaxis=dict(
        title="Order Month",
        titlefont=dict(
            size=14,
        ),
        tickfont=dict(
            size=14,
        ),
    ),
    yaxis=dict(
        title="Number of orders",
        titlefont=dict(
            size=14,
        ),
        tickfont=dict(
            size=14,
        ),
    ),
    width=1200,
    height=900,
)

fig.show()



Tingkat penjualan di tahun 2016 tidak dapat diamati dengan baik dikarenakan ketidaklengkapan data yang ada. Yaitu hanya terdapat 1 transaksi pada bulan Desember 2016.

In [147]:
df_tingkat_penjualan_2017 = all_df[all_df.order_year == 2017]

tingkat_penjualan_2017 = df_tingkat_penjualan_2017.groupby(by='order_month').agg({
    "order_id": "nunique",
    "order_month_name" : pd.Series.mode,
    "payment_value" : "sum"
}).sort_values(by="order_month").reset_index()

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=tingkat_penjualan_2017["order_month_name"],
    y=tingkat_penjualan_2017["order_id"],
    mode='lines+markers',
    marker=dict(
        color='red',
        size=8,
    ),
    line=dict(
        width=3,
    ),
))

for x, y in zip(tingkat_penjualan_2017["order_month_name"], tingkat_penjualan_2017["order_id"]):
    fig.add_annotation(
        x=x,
        y=y+150,
        text=str(y),
        font=dict(
            size=12,
        ),
        showarrow=False,
        textangle=0,
    )

fig.update_layout(
    title="Tingkat Penjualan Tahun 2017",
    xaxis=dict(
        title="Order Month",
        titlefont=dict(
            size=14,
        ),
        tickfont=dict(
            size=14,
        ),
    ),
    yaxis=dict(
        title="Number of orders",
        titlefont=dict(
            size=14,
        ),
        tickfont=dict(
            size=14,
        ),
    ),
    width=1200,
    height=900,
)

fig.show()

Tingkat penjualan pada tahun 2017 menunjukan tren pertumbuhan yang baik hingga akhir tahun. Bulan november merupakan bulan yang memiliki jumlah transaksi tertinggi yaitu sebesar 7146 transaksi dengan total penjualan selama 1 tahun sebesar 43352 dan total pemasukan dari keseluruhan transaksi sebesar 8 juta USD atau sekitar 121 milyar rupiah.

In [148]:
df_tingkat_penjualan_2018 = all_df[all_df.order_year == 2018]

tingkat_penjualan_2018 = df_tingkat_penjualan_2018.groupby(by='order_month').agg({
    "order_id": "nunique",
    "order_month_name" : pd.Series.mode,
    "payment_value" : "sum"
}).sort_values(by="order_month").reset_index()

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=tingkat_penjualan_2018["order_month_name"],
    y=tingkat_penjualan_2018["order_id"],
    mode='lines+markers',
    marker=dict(
        color='red',
        size=8,
    ),
    line=dict(
        width=3,
    ),
))

for x, y in zip(tingkat_penjualan_2018["order_month_name"], tingkat_penjualan_2018["order_id"]):
    fig.add_annotation(
        x=x,
        y=y+150,
        text=str(y),
        font=dict(
            size=12,
        ),
        showarrow=False,
        textangle=0,
    )

fig.update_layout(
    title="Tingkat Penjualan Tahun 2018",
    xaxis=dict(
        title="Order Month",
        titlefont=dict(
            size=14,
        ),
        tickfont=dict(
            size=14,
        ),
    ),
    yaxis=dict(
        title="Number of orders",
        titlefont=dict(
            size=14,
        ),
        tickfont=dict(
            size=14,
        ),
    ),
    width=1200,
    height=900,
)

fig.show()

Tingkat penjualan pada tahun 2018 menujukan tren yang cukup stagnan dan cenderung turun dengan bulan maret menjadi bulan yang memiliki jumlah transaksi tertinggi yaitu sebesar 7085 transaksi.dengan total penjualan selama 1 tahun sebesar 52859 dan total pemasukan dari keseluruhan transaksi sebesar 10 juta USD atau sekitar 151 milyar rupiah.

## 10 Produk Teratas Yang Memiliki Pendapatan Tertinggi

In [149]:
df_product_sales = all_df.groupby(by="product_name").agg({
    "payment_value": "sum",
}).nlargest(10, "payment_value").round().reset_index()

fig = go.Figure()

fig.add_trace(go.Bar(
    x=df_product_sales['product_name'],
    y=df_product_sales['payment_value'],
    marker=dict(
        color='rgb(173, 216, 230)',  # Set color here
    ),
))

for i, v in enumerate(df_product_sales['payment_value']):
    fig.add_annotation(
        x=df_product_sales['product_name'][i],
        y=v+5,
        text=str(v),
        font=dict(
            size=10,
            color='black',  # Set text color here
        ),
        showarrow=False,
        textangle=0,
        align='center',
    )

fig.update_layout(
    title='Top 10 Best Selling Products 2016 - 2018',
    xaxis=dict(
        title='Product Name',
        tickangle=45,
        tickfont=dict(
            size=12,
        ),
        automargin=True,
    ),
    yaxis=dict(
        title='Total Sales',
        tickformat='plain',
        tickfont=dict(
            size=12,
        ),
    ),
    
    showlegend=False,
)

fig.show()

- 10 produk yang memiliki banyak peminat yaitu bed bath table, health beauty, computers accesories, furniture decor, watches gifts, sports leisure, housewares, garden tools, auto, dan cool stuff.

- Produk dengan penjualan tertinggi adalah bed bath table dengan jumlah penjualan 1725466 barang.

## 10 Produk Yang Memiliki Pendapatan Terendah

In [150]:
df_product_sales = all_df.groupby(by="product_name").agg({
    "payment_value": "sum",
}).nsmallest(10, "payment_value").round().reset_index()

fig = go.Figure()

fig.add_trace(go.Bar(
    x=df_product_sales['product_name'],
    y=df_product_sales['payment_value'],
    marker=dict(
        color='rgb(173, 216, 230)',  # Set color here
    ),
))

for i, v in enumerate(df_product_sales['payment_value']):
    fig.add_annotation(
        x=df_product_sales['product_name'][i],
        y=v+5,
        text=str(v),
        font=dict(
            size=10,
            color='black',  # Set text color here
        ),
        showarrow=False,
        textangle=0,
        align='center',
    )

fig.update_layout(
    title='Top 10 Best Selling Products 2016 - 2018',
    xaxis=dict(
        title='Product Name',
        tickangle=45,
        tickfont=dict(
            size=12,
        ),
        automargin=True,
    ),
    yaxis=dict(
        title='Total Sales',
        tickformat='plain',
        tickfont=dict(
            size=12,
        ),
    ),
    
    showlegend=False,
)

fig.show()

- 10 produk yang memiliki sedikit peminat yaitu security and service, fashion childrens clothes, cds dvds musicals, home comfort, flowers, art and craftmanship, la cuisine, fashion sport, diapers and hygiene, fashion female clothing.

- Produk dengan penjualan terendah adalah security and service dengan jumlah penjualan 325 barang.

## Bagaimana pesebaran daerah tempat pelanggan yang melakukan transaksi ?

In [151]:
bystate_df = all_df.groupby(by="customer_city").agg({
    "order_id": "nunique",
    "payment_value": "sum",
    "product_name": pd.Series.mode
}).nlargest(10, "order_id").reset_index()
bystate_df.rename(columns={
    "order_id": "customer_count"
}, inplace=True)

fig = go.Figure()

fig.add_trace(go.Bar(
    x=bystate_df['customer_count'],
    y=bystate_df['customer_city'],
    orientation='h',
    marker=dict(
        color=["#72BCD4", "#D3D3D3", "#D3D3D3", "#D3D3D3", "#D3D3D3", "#D3D3D3", "#D3D3D3", "#D3D3D3", "#D3D3D3", "#D3D3D3"],
    ),
    text=bystate_df['customer_count'],  # Menambahkan teks berdasarkan jumlah penjual
    textposition='auto',  # Menyesuaikan posisi teks secara otomatis
))

fig.update_layout(
    title='Number of customer by States',
    xaxis=dict(
        title='customer Count',
        tickfont=dict(
            size=12,
        ),
    ),
    yaxis=dict(
        tickfont=dict(
            size=12,
        ),
        automargin=True,
    ),
    width=750,
    height=500,
)

fig.show()

- Sao Bernando Campo memiliki pelanggan terendah dari 10 wilayah, dengan jumlah 907 jiwa

- Sao Paulo memiliki pelanggan tertinggi dari 10 wilayah, dengan jumlah 15045 jiwa


## Bagaimana pesebaran daerah tempat seller yang melakukan transaksi ?

In [152]:
bystate_df = all_df.groupby(by="seller_city").agg({
    "order_id": "nunique",
    "payment_value": "sum",
    "product_name": pd.Series.mode
}).nlargest(10, "order_id").reset_index()
bystate_df.rename(columns={
    "order_id": "seller_count"
}, inplace=True)

fig = go.Figure()

fig.add_trace(go.Bar(
    x=bystate_df['seller_count'],
    y=bystate_df['seller_city'],
    orientation='h',
    marker=dict(
        color=["#72BCD4", "#D3D3D3", "#D3D3D3", "#D3D3D3", "#D3D3D3", "#D3D3D3", "#D3D3D3", "#D3D3D3", "#D3D3D3", "#D3D3D3"],
    ),
    text=bystate_df['seller_count'],  # Menambahkan teks berdasarkan jumlah penjual
    textposition='auto',  # Menyesuaikan posisi teks secara otomatis
))

fig.update_layout(
    title='Number of seller by States',
    xaxis=dict(
        title='seller Count',
        tickfont=dict(
            size=12,
        ),
    ),
    yaxis=dict(
        tickfont=dict(
            size=12,
        ),
        automargin=True,
    ),
    width=750,
    height=500,
)
fig.show()

- Guarulhos memiliki penjual terendah dari 10 wilayah, dengan jumlah 1694 penjual

- Sao Paulo memiliki penjual tertinggi dari 10 wilayah, dengan jumlah 24215 penjual

## jenis pembayaran apa yang paling banyak digunakan pelanggan ?

In [153]:
df_payment_type = all_df.groupby(by="payment_type").agg({
    "customer_id": "count",
}).reset_index()


fig = go.Figure()
fig.add_trace(go.Bar(
    x=df_payment_type['payment_type'],
    y=df_payment_type['customer_id'],
    text=df_payment_type['customer_id'],  # Menambahkan label di setiap bar
    textposition='outside',  # Menampilkan label di luar bar
    textfont=dict(
        color='white',  # Mengatur warna teks menjadi putih
    ),
    marker=dict(
        color='rgb(173, 216, 230)',  # Set color here
    ),
))
fig.update_layout(
    title='Customer Payment Type Over 2016 - 2018',
    xaxis=dict(title='Product Name', tickangle=45),
    yaxis=dict(title='Total Sales'),
    showlegend=False,
    width=700,
    height=500,
)

- Jenis pembayaran yang paling banyak digunakan pelanggan adalah credit card dan juga boleto dengan jumlah transaksi sebanyak 85277 dan 22510 transaksi pada masing - masing jenis pembayaran tersbut.

- Jenis pembayaran yang paling sedikit digunakan pelanggan adalah debit card dan voucher yaitu hanya sebesar 1659 dan 6162 transaksi pada masing - masing jenis pembayaran tersbut.

## Kapan waktu yang paling banyak pelanggan yang melakukan transaksi ? (pagi/siang/sore/malam)

In [154]:
df_product_sales = all_df.groupby(by="order_purchase_time").agg({
    "customer_id": "count"
}).sort_values(by="customer_id",ascending=False).reset_index()
fig = go.Figure(data=[
    go.Bar(x=df_product_sales['order_purchase_time'], y=df_product_sales['customer_id'], marker_color='rgb(173, 216, 230)')
])
fig.update_layout(
    title='Top 10 Best Worst Products 2016 - 2018',
    xaxis=dict(title='Product Name', tickangle=45),
    yaxis=dict(title='Total Sales'),
    showlegend=False
)
fig.update_traces(texttemplate='%{y}', textposition='outside')
fig.show()

Waktu transaksi pelanggan paling banyak dilakukan pada pagi hari yaitu sebesar 44871 transaksi.

Waktu transaksi pelanggan paling sedikit adalah pada malam hari yaitu hanya sebesar 10112 transaksi.

## Berapa banyak jumlah transaksi yang sampai tepat waktu, lebih cepat atau lebih lambat daripada waktu perkiraan pengiriman ?

In [155]:
df_product_sales = all_df.groupby(by="delivery_status").agg({
    "order_id": "count"
}).sort_values(by="order_id",ascending=False).reset_index()

fig = go.Figure(data=[
    go.Bar(x=df_product_sales['delivery_status'], y=df_product_sales['order_id'], marker_color='rgb(173, 216, 230)')
])
fig.update_layout(
    title='Order Delivery Status Over 2016 - 2018',
    xaxis=dict(title='Product Name', tickangle=45),
    yaxis=dict(title='Order Count'),
    showlegend=False
)
fig.update_traces(texttemplate='%{y}', textposition='outside')
fig.show()

- Hampir sebagian besar produk yaitu sejumlah 106893 produk yang terjual berhasil sampai ke pelanggan dengan tepat waktu.

- Masih ada sebesar 8715 barang yang masih terlambat untuk sampai ke pelanggan.

# RFM ANALYSIS

In [158]:
all_df = pd.read_csv("dashboard/all_data.csv")

In [159]:
datetime_columns = ["order_approved_at","order_delivered_carrier_date",'order_delivered_customer_date','order_estimated_delivery_date' ]
 
for column in datetime_columns:
  all_df[column] = pd.to_datetime(all_df[column])
  all_df[column] = all_df[column].dt.date
  all_df[column] = pd.to_datetime(all_df[column])
all_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115608 entries, 0 to 115607
Data columns (total 45 columns):
 #   Column                         Non-Null Count   Dtype         
---  ------                         --------------   -----         
 0   order_id                       115608 non-null  object        
 1   customer_id                    115608 non-null  object        
 2   order_status                   115608 non-null  object        
 3   order_purchase_timestamp       115608 non-null  int64         
 4   order_approved_at              115608 non-null  datetime64[ns]
 5   order_delivered_carrier_date   115608 non-null  datetime64[ns]
 6   order_delivered_customer_date  115608 non-null  datetime64[ns]
 7   order_estimated_delivery_date  115608 non-null  datetime64[ns]
 8   delivery_status                115608 non-null  object        
 9   order_item_id                  115608 non-null  int64         
 10  product_id                     115608 non-null  object        
 11  

In [160]:
df_recency = all_df.groupby(by='customer_id',as_index=False)['order_approved_at'].max()
df_recency.columns = ['CustomerId', 'LastPurchaseDate']
recent_date = df_recency['LastPurchaseDate'].max()
df_recency['Recency'] = df_recency['LastPurchaseDate'].apply(
    lambda x: (recent_date - x).days)
df_recency.head()

CustomerId LastPurchaseDate  Recency
0  00012a2ce6f8dcda20d059ce98491703       2017-11-14      293
1  000161a058600d5901f007fab4c27140       2017-07-16      414
2  0001fd6190edaaf884bcaf3d49edf079       2017-02-28      552
3  0002414f95344307404f0ace7a26f1d5       2017-08-17      382
4  000379cdec625522490c315e70c7a9fb       2018-04-04      152

In [161]:
frequency_df = all_df.drop_duplicates().groupby(
    by=['customer_id'], as_index=False)['order_approved_at'].count()
frequency_df.columns = ['CustomerId', 'Frequency']
frequency_df.head()

CustomerId  Frequency
0  00012a2ce6f8dcda20d059ce98491703          1
1  000161a058600d5901f007fab4c27140          1
2  0001fd6190edaaf884bcaf3d49edf079          1
3  0002414f95344307404f0ace7a26f1d5          1
4  000379cdec625522490c315e70c7a9fb          1

In [162]:
monetary_df = all_df.groupby(by='customer_id', as_index=False)['payment_value'].sum()
monetary_df.columns = ['CustomerId', 'Monetary']
monetary_df.head()

CustomerId  Monetary
0  00012a2ce6f8dcda20d059ce98491703    114.74
1  000161a058600d5901f007fab4c27140     67.41
2  0001fd6190edaaf884bcaf3d49edf079    195.42
3  0002414f95344307404f0ace7a26f1d5    179.35
4  000379cdec625522490c315e70c7a9fb    107.01

In [163]:
rf_df = df_recency.merge(frequency_df, on='CustomerId')
rfm_df = rf_df.merge(monetary_df, on='CustomerId').drop(
    columns='LastPurchaseDate')
rfm_df.head()

CustomerId  Recency  Frequency  Monetary
0  00012a2ce6f8dcda20d059ce98491703      293          1    114.74
1  000161a058600d5901f007fab4c27140      414          1     67.41
2  0001fd6190edaaf884bcaf3d49edf079      552          1    195.42
3  0002414f95344307404f0ace7a26f1d5      382          1    179.35
4  000379cdec625522490c315e70c7a9fb      152          1    107.01

In [164]:
rfm_df['R_rank'] = rfm_df['Recency'].rank(ascending=False)
rfm_df['F_rank'] = rfm_df['Frequency'].rank(ascending=True)
rfm_df['M_rank'] = rfm_df['Monetary'].rank(ascending=True)
 
# normalizing the rank of the customers
rfm_df['R_rank_norm'] = (rfm_df['R_rank']/rfm_df['R_rank'].max())*100
rfm_df['F_rank_norm'] = (rfm_df['F_rank']/rfm_df['F_rank'].max())*100
rfm_df['M_rank_norm'] = (rfm_df['F_rank']/rfm_df['M_rank'].max())*100
 
rfm_df.drop(columns=['R_rank', 'F_rank', 'M_rank'], inplace=True)

rfm_df.head()

CustomerId  Recency  Frequency  Monetary  \
0  00012a2ce6f8dcda20d059ce98491703      293          1    114.74   
1  000161a058600d5901f007fab4c27140      414          1     67.41   
2  0001fd6190edaaf884bcaf3d49edf079      552          1    195.42   
3  0002414f95344307404f0ace7a26f1d5      382          1    179.35   
4  000379cdec625522490c315e70c7a9fb      152          1    107.01   

   R_rank_norm  F_rank_norm  M_rank_norm  
0    34.145697    43.478734    43.478734  
1    16.669516    43.478734    43.478734  
2     2.768150    43.478734    43.478734  
3    21.142179    43.478734    43.478734  
4    67.306507    43.478734    43.478734

In [165]:
rfm_df['RFM_Score'] = 0.15*rfm_df['R_rank_norm']+0.28 * \
    rfm_df['F_rank_norm']+0.57*rfm_df['M_rank_norm']
rfm_df['RFM_Score'] *= 0.05
rfm_df = rfm_df.round(2)
rfm_df[['CustomerId', 'RFM_Score']].head(7)

CustomerId  RFM_Score
0  00012a2ce6f8dcda20d059ce98491703       2.10
1  000161a058600d5901f007fab4c27140       1.97
2  0001fd6190edaaf884bcaf3d49edf079       1.87
3  0002414f95344307404f0ace7a26f1d5       2.01
4  000379cdec625522490c315e70c7a9fb       2.35
5  0004164d20a9e969af783496f3408652       1.90
6  000419c5494106c306a97b5635748086       2.30

In [166]:
rfm_df["Customer_segment"] = np.where(rfm_df['RFM_Score'] >
                                      4.5, "Top Customers",
                                      (np.where(
                                        rfm_df['RFM_Score'] > 4,
                                        "High value Customer",
                                        (np.where(
    rfm_df['RFM_Score'] > 3,
                             "Medium Value Customer",
                             np.where(rfm_df['RFM_Score'] > 1.6,
                            'Low Value Customers', 'Lost Customers'))))))
rfm_df[['CustomerId', 'RFM_Score', 'Customer_segment']].head(20)

CustomerId  RFM_Score     Customer_segment
0   00012a2ce6f8dcda20d059ce98491703       2.10  Low Value Customers
1   000161a058600d5901f007fab4c27140       1.97  Low Value Customers
2   0001fd6190edaaf884bcaf3d49edf079       1.87  Low Value Customers
3   0002414f95344307404f0ace7a26f1d5       2.01  Low Value Customers
4   000379cdec625522490c315e70c7a9fb       2.35  Low Value Customers
5   0004164d20a9e969af783496f3408652       1.90  Low Value Customers
6   000419c5494106c306a97b5635748086       2.30  Low Value Customers
7   00046a560d407e99b969756e0b10f282       2.17  Low Value Customers
8   00050bf6e01e69d5c0fd612f1bcfb69c       2.04  Low Value Customers
9   000598caf2ef4117407665ac33275130       2.57  Low Value Customers
10  0005aefbb696d34b3424dccd0a0e9fd0       2.48  Low Value Customers
11  00062b33cb9f6fe976afdcff967ea74d       1.88  Low Value Customers
12  00066ccbe787a588c52bd5ff404590e3       4.61        Top Customers
13  00072d033fe2e59061ae5c3aff1a2be5       2.02  Low Value Customers
14  0009a69b72033b2d0ec8c69fc70ef768       1.91  Low Value Customers
15  000bf8121c3412d3057d32371c5d3395       4.12  High value Customer
16  000e943451fc2788ca6ac98a682f2f49       4.25  High value Customer
17  000f17e290c26b28549908a04cfe36c1       2.10  Low Value Customers
18  000fd45d6fedae68fc6676036610f879       2.37  Low Value Customers
19  0010068a73b7c56da5758c3f9e5c7375       1.90  Low Value Customers

In [167]:
import plotly.graph_objects as go
# Count the occurrences of each segment
segment_counts = rfm_df['Customer_segment'].value_counts()
# Define a pastel color palette
color_palette = ['#B7D7D8', '#F3B1B3', '#B5B8C3', '#F9D9B4']
# Create a Pie chart trace
pie_trace = go.Pie(
    labels=segment_counts.index,
    values=segment_counts.values,
    hovertemplate='Segment: %{label}<br>Count: %{value}<br>Percentage: %{percent}',
    textinfo='percent',
    textposition='inside',  # Set the label position to 'inside'
    textfont=dict(size=12),
    marker=dict(
        colors=color_palette,
        line=dict(color='#000000', width=1)
    )
)
# Create the layout
layout = go.Layout(
    title='Customer Segmentation',
    width=700,  # Adjust the width of the chart
    height=500  # Adjust the height of the chart
)
# Create the figure
fig = go.Figure(data=[pie_trace], layout=layout)
# Show the figure
fig.show()


- Sebagian besar pelanggan adalah pelanggan dengan indeks 'Low Value Customer' yang berarti ia memiliki nilai RFM score dibawah 1.6 yang bisa dibilang sangat rendah. Hal tersebut disebabkan kaarena banyak sekali customer yang hanya melakukan transaksi sebanyak 1 kali dan tidak pernah melakukan transaksi lagi selama rentang tahun 2016 - 2018.

- Hanya 3.52% dari keseluruhan pelanggan yang termasuk kedalam 'Top customer' dan hanya sebesar 8.14% yang termasuk kedalam 'High Value Customer'.